### ISSUE TITLE
Make MongoDB processing optional

### ISSUE THREAD

**Issue by jmmec** [kubedb/project#1039]
We have a software release that uses KubeDB for managing elasticsearch, but not for Mongo.  KubeDB will intermittently generate debug logs that reference Mongo even when Mongo is not deployed or used.  Please consider a future enhancement to KubeDB that makes MongoDB processing optional (say based on a helm variable or whatever).  

Thank you!

**Comment by tamalsaha** [comment]
This is supported in KubeDB v2024.1.31 release. You can enable/disable any database support via values file

https://github.com/kubedb/installer/blob/8c979fc3bb145a9e1f075e487129d810540a29cf/charts/kubedb/values.yaml#L43-L62
