### ISSUE TITLE
Handling CRD object one by one

### ISSUE THREAD

**Issue by aerokite** [kubedb/project#105]
I have created 3 Elasticsearch objects at a time with the different name. The controller is handling these 3 object one by one. When the controller is done with the 1st object, it starts processing 2nd one. Is it correct behavior? @tamalsaha 

The same object should wait in the queue. But different objects can be de-queue simultaneously. right?

**Comment by aerokite** [comment]
cc: @the-redback

**Comment by tamalsaha** [comment]
Yes, since we have used threadiness = 1. We have only one go routine handling stuff at a time.

For parallel processing, we need to increase the threadiness value.

**Comment by aerokite** [comment]
I understood that later. We can pass this as a flag. I'm closing this issue.
