### ISSUE TITLE
The hyphen required for this command was replaced with the html entity causing error when executing (&ndash; vs -).

### ISSUE THREAD

**Issue by mateothegreat** [kubedb/project#119]
Documentation referencing 

The hyphen required for this command was replaced with the html entity causing error when executing (&ndash; vs -).

It appears the markup looks fine .. it's the sites markup itself.

![image](https://user-images.githubusercontent.com/11623940/35733585-908ca126-07e3-11e8-83eb-7003817d151f.png)

**Comment by tamalsaha** [comment]
This should be fixed with https://github.com/kubedb/cli/releases/tag/0.8.0-beta.2. Please reopen if you are still seeing this problem.
