### ISSUE TITLE
Tag 0.8.0 not found in repository docker.io/kubedb/operator.

### ISSUE THREAD

**Issue by mateothegreat** [kubedb/project#120]
Error when installing operator using latest version:

Failed to pull image "kubedb/operator:0.8.0": rpc error: code = Unknown desc = Tag 0.8.0 not found in repository docker.io/kubedb/operator.

No tag matching tags available at https://hub.docker.com/r/kubedb/operator/tags/.

**Comment by the-redback** [comment]
Hi @mateothegreat ,
version 0.8.0 has not been released yet. We need to fix this bug in `kubedb cli`.

Meanwhile, you can follow the alternative way to deploy `kubedb-operator`.
Run the following command to deploy latest (0.8.0-beta.0) operator:
```console
$ kubedb init --version='0.8.0-beta.0'
```

Please note that If there is already a deployment exists of `kubedb-operator`, you can upgrade that by:
```console
$ kubedb init --version='0.8.0-beta.0' --upgrade
````

**Comment by the-redback** [comment]
cc: @tamalsaha 

https://github.com/kubedb/cli/blob/0.8.0-beta.0/pkg/util/flags.go#L49

**Comment by tamalsaha** [comment]
Fixed in master
