### ISSUE TITLE
Use "elasticsearches"  as resource type of Elasticsearch

### ISSUE THREAD

**Issue by aerokite** [kubedb/project#125]
As Kubernetes didn't support, we used `elasticsearchs` as plural of Elasticsearch.

	ResourceCodeElasticsearch   = "es"
	ResourceKindElasticsearch   = "Elasticsearch"
	ResourceNameElasticsearch   = "elasticsearch"
	ResourceTypeElasticsearch   = "elasticsearchs"

Should we use `elasticsearches` as its the correct plural form?

**Comment by tamalsaha** [comment]
yes. This has been fixed in Kube 1.9.
https://github.com/kubernetes/apiextensions-apiserver/issues/12#issuecomment-357756880

Also code generator has been fixed 26 days ago. https://github.com/kubernetes/gengo/commit/620d1a032ac0475048b02bd1f0bf1067a3c7679d#diff-5ae98d3146dd4ccc40a12538a05637b9R64

**Comment by tamalsaha** [comment]
- [ ] Also need to update the apiserver Webhook config
https://github.com/kubedb/cli/blob/master/hack/deploy/admission.yaml#L19
