### ISSUE TITLE
Cut release 'v0.1.7' for wal-g

### ISSUE THREAD

**Issue by aerokite** [kubedb/project#129]
Upstream: https://github.com/wal-g/wal-g/tree/v0.1.7

Added support for PostgreSQL version `10.2`. 

KubeDB Postgres will use latest `wal-g` version

Support of Postgres `10.2`: https://github.com/kubedb/postgres/pull/123

**Comment by tamalsaha** [comment]
https://github.com/kubedb/wal-g/releases/tag/v0.1.7
