### ISSUE TITLE
Support Elasticsearch 6.x

### ISSUE THREAD

**Issue by aerokite** [kubedb/project#133]

**Comment by tamalsaha** [comment]
https://www.elastic.co/blog/doubling-down-on-open

**Comment by stormmore** [comment]
Would it be better to skip 6.2 and go to 6.3? My team is telling me that 6.3 has a lot of functionality that would make their lives easier

As a side note, my team is already looking at 7.

**Comment by tamalsaha** [comment]
Sure. once we add that we move to 6.3 directly.

**Comment by stormmore** [comment]
This is now a blocker for our adoption for ES backends

**Comment by stormmore** [comment]
Initial PR for container creation: https://github.com/kubedb/elasticsearch/pull/142

**Comment by tamalsaha** [comment]
https://github.com/kubedb/elasticsearch/pull/143

**Comment by jalberto** [comment]
any news about support for ES 6.3?
