### ISSUE TITLE
Feature Request: Inject database user credentials into deployments with database clients

### ISSUE THREAD

**Issue by jensneuse** [kubedb/project#141]
It would be useful to have some kind of annotation to indicate to the operator that a container needs client credentials with specific rights to a kubedb managed database.

Once submitting an annotated deployment to the kubernetes api the kubedb operator should intercept the deployment. It should generate credentials (at the database level) and inject them according to the annotations as environment variables into the deployment/container. On container deletion the operator should automatically cleanup the created database roles.

For security reasons the initial database deployment could be enhanced with role bindings between the database and kubernetes service accounts, so that it's only possible to get credentials injected into the database client container when the deployment serviceAccount matches the ones declared with the database kind.

**Comment by tamalsaha** [comment]
https://www.youtube.com/watch?v=E75FGtAEvQw

**Comment by tamalsaha** [comment]
Design decisions:
- If Role is deleted, RoleBindings are not deleted.
- If Role is updated, credentials must be reissued.
- If Role is deleted, credentials must be revoked.

**Comment by tamalsaha** [comment]
- [ ] Create PolicyBinding for DBRoleBinding

**Comment by tamalsaha** [comment]
This has been implemented in https://github.com/kubevault/operator/pull/123

**Comment by tamalsaha** [comment]
@jensneuse , this issue is resolved https://twitter.com/kubevault/status/1101441514108928001
