### ISSUE TITLE
X-pack

### ISSUE THREAD

**Issue by tamalsaha** [kubedb/project#142]
## Security via x-pack

```
type AuthPlugin string

const (
	AuthPluginNone AuthPlugin = "None"
	AuthPluginSearchGuard AuthPlugin = "SearchGuard"
	AuthPluginXpack AuthPlugin = "Xpack"
)
```

```
kind: Elasticsearch
spec:
  authProvider:  
```

If spec.authProvider is unset (empty string), it defaults to `SearchGuard` .

## Monitoring via x-pack
```
type AgentSpec struct {
	// Valid values: coreos-prometheus-operator
	Agent      AgentType       `json:"agent,omitempty"`
	Prometheus *PrometheusSpec `json:"prometheus,omitempty"`
}
```

https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-xpack.html

**Comment by jalberto** [comment]
yes please, x-pack support is very necessary.

From version 6.3 it will be included as opensource in ES https://www.elastic.co/products/x-pack/open

**Comment by uipo78** [comment]
just so that this is visible on both slack and github --  I'm willing to tackle this issue!

**Comment by tamalsaha** [comment]
xref: https://github.com/kubedb/project/issues/165

**Comment by tamalsaha** [comment]
Here is a proposal for installing custom extensions

https://github.com/kubedb/project/issues/183#issuecomment-409715800

**Comment by hossainemruz** [comment]
@jalberto and @uipo78 which x-pack features are you wiling to use with KubeDB Elasticsearch. Only Monitoring, tile maps, Grok Debugger, and Search Profiler are available in free tire. Authentication using x-pack is a paid feature. Ref: https://www.elastic.co/guide/en/elasticsearch/reference/current/configuring-security.html

**Comment by jalberto** [comment]
@hossainemruz I am only interested in the free features you mentioned, I prefer my auth layer to be centralized and not in each service I use.

**Comment by tamalsaha** [comment]
>  I am only interested in the free features you mentioned,

This will be possible using the custom config support in 0.9.0 . We will revisit auth support via x-pack in a later time as part of https://github.com/kubedb/user-manager.
