### ISSUE TITLE
ElasticSearch PVC can be allocated separately

### ISSUE THREAD

**Issue by aland-zhang** [kubedb/project#151]
ElasticSearch PVC can be allocated separately ，because master and client nodes do not need  Storage as much as Data nodes，so master and client nodes need to set a smaller storage.
Please refer to ：
https://github.com/jetstack/navigator/blob/master/docs/quick-start/es-cluster-demo.yaml
**such as:**
apiVersion: kubedb.com/v1alpha1
kind: Elasticsearch
metadata:
  name: topology-es
  namespace: demo
spec:
  version: 5.6
  topology:
    **master:**
      prefix: master
      replicas: 1
      storage:
        storageClassName: "standard"
        accessModes:
        - ReadWriteOnce
        resources:
        requests:
           storage: 50Mi
    **data:**
      prefix: data
      replicas: 5
      storage:
        storageClassName: "standard"
        accessModes:
        - ReadWriteOnce
        resources:
        requests:
           storage: 20Gi
    **client:**
      prefix: client
      replicas: 2
      storage:
        storageClassName: "standard"
        accessModes:
        - ReadWriteOnce
        resources:
        requests:
           storage: 50Mi

**Comment by tamalsaha** [comment]
Fixed in 0.8.0 . Supported here: https://github.com/kubedb/apimachinery/blob/master/apis/kubedb/v1alpha1/elasticsearch_types.go#L129
