### ISSUE TITLE
KubeDB server crash with cluster CA 

### ISSUE THREAD

**Issue by valentin2105** [kubedb/project#157]
Hi,

I try KubeDB on my cluster with the Helm charts (stable or appscodes one) : 

```
helm install stable/kubedb --name kubedb \      
  --set apiserver.ca="$(onessl get kube-ca)"
```

```
$ - k logs -f kubedb-7866859c8f-6x6xt server
--help ...
I0506 22:34:13.487988       1 logs.go:19] cluster doesn't provide requestheader-client-ca-file
```

The `onessl` command correctly retrieve my CA. 

Any idea where it's wrong ? 

Thanks .

**Comment by tamalsaha** [comment]
@valentin2105 , you have to enable aggregate api server feature in your cluster. You can find discussion on this topic here: https://github.com/appscode/stash/issues/353#issuecomment-368782830

**Comment by valentin2105** [comment]
That was the problem.

The cluster was provisionned with my bare hand :)

Thanks !!!
