### ISSUE TITLE
incorrect calls in MySql quick start 

### ISSUE THREAD

**Issue by MarkHultermans** [kubedb/project#164]
in a number of examples on the page https://kubedb.com/docs/0.8.0-rc.0/guides/mysql/quickstart/quickstart/ the commands like "kubedb get my -n demo -o yaml  --show-all" are mentioned but this is on my installation only working when I use "kubedb get mysql -n demo -o yaml  --show-all"

**Comment by tamalsaha** [comment]
@the-redback @sajibcse68 can you check this?

**Comment by the-redback** [comment]
Hi @MarkHultermans, 

This `kubedb` command works fine on my machine. 
Can you show the output of following command?

```
$ kubedb version
```

**Comment by MarkHultermans** [comment]
Hi Maruf, here are the results 

mbp-van-mark:~ markhultermans$ kubedb version
Version = 0.8.0-beta.0
VersionStrategy = tag
Os = darwin
Arch = amd64
CommitHash = a1cf025d171a6039f6cf05e0163e05deecca9081
GitBranch = release-0.8
GitTag = 0.8.0-beta.0
CommitTimestamp = 2018-01-07T07:29:57

mbp-van-mark:~ markhultermans$ kubedb get my -n demo -o yaml --show-all
error: kubedb doesn't support a resource type "my"

mbp-van-mark:~ markhultermans$ kubedb get mysql -n demo -o yaml
--show-all
apiVersion: kubedb.com/v1alpha1
kind: MySQL
metadata:
clusterName: ""
creationTimestamp: 2018-05-29T14:52:36Z
finalizers:
- kubedb.com
generation: 1
name: mysql-init-script
namespace: demo
resourceVersion: "31991"

  Best regards, Mark Hultermans
Maruf Tuhin schreef op 30 mei '18:

> Hi @MarkHultermans [1], 
> 
> This kubedb command works fine on my machine.
> Can you show the output of following command?
> 
> $ kubedb version
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [2], or mute the thread [3].
 

Links:
------
[1] https://github.com/MarkHultermans
[2] https://github.com/kubedb/project/issues/164#issuecomment-393029069
[3]

**Comment by the-redback** [comment]
@MarkHultermans , We have released a newer version of `kubedb cli` as well which is `0.8.0-rc.0`.
Install the newer version from [here](https://kubedb.com/docs/0.8.0-rc.0/setup/install/#install-kubedb-cli). let us know if you still face this problem.
