### ISSUE TITLE
Percona support in kubedb mysql

### ISSUE THREAD

**Issue by devdattakulkarni** [kubedb/project#169]
Hi,

For our use-case we need to use Percona cluster. I was wondering if kubedb operator supports handling of Percona backups, restore, etc. as part of the MySQL CRD?

Thanks!

**Comment by tamalsaha** [comment]
We don't yet. But we are open to adding. We just had time to work on that.

**Comment by tamalsaha** [comment]
Dup https://github.com/kubedb/project/issues/18
