### ISSUE TITLE
Gitrepo volume is getting deprecated.

### ISSUE THREAD

**Issue by tamalsaha** [kubedb/project#170]
- We need to update our examples to use newly recommended method. (init containers)

https://github.com/kubernetes/kubernetes/issues/60999

https://gist.github.com/tallclair/849601a16cebeee581ef2be50c351841

**Comment by tamalsaha** [comment]
```
kubectl create configmap my-config \
  --from-literal=key1=$(curl -fsSL <raw_url>)

```

**Comment by the-redback** [comment]
- [ ] Postgres
- [ ] Elasticsearch
- [ ] MongoDB
- [ ] MySQL
- [ ] Redis
