### ISSUE TITLE
Problems installing kubedb on kubespray provisioned cluster

### ISSUE THREAD

**Issue by emilingerslev** [kubedb/project#177]
Going through the Quickstart for kubedb installing either a postgres or redis database fails on my kubespray provisioned kubernetes cluster.

* Kubespray version:  master (https://github.com/kubernetes-incubator/kubespray/tree/cf8e9eed6959fe695b6afe3c8dede57b8a31abc0)
* Kubernetes version 1.9.7

Tried to setup kubedb using the bash script which went well, but when setting up the databases through CRD's I got the following result describing the resources:

    kubedb -n limbo-review get pg,redis -o wide
    NAME                 VERSION   STATUS    AGE
    pg/quick-postgres    9.6       Unknown   34m
    
    NAME                  VERSION   STATUS    AGE
    rd/redis-quickstart   4         Unknown   2m

Looking at the logs for the kubedb-operator I got:

    I0612 07:04:29.463933       1 wrap.go:42] POST /apis/mutators.kubedb.com/v1alpha1/postgreses: (8.68488ms) 201 [[Go-http-client/2.0] 10.233.64.1:53868]
    I0612 07:04:29.519922       1 wrap.go:42] POST /apis/validators.kubedb.com/v1alpha1/postgreses: (51.576546ms) 201 [[Go-http-client/2.0] 10.233.64.1:53868]
    I0612 07:04:29.552116       1 postgres.go:59] Patching Postgres limbo-review/quick-postgres2 with {"metadata":{"finalizers":["kubedb.com"]}}.
    E0612 07:04:29.556993       1 postgres.go:33] [object 'Version' is missing in '{ <nil> <nil> <nil> <nil> nil {[] nil {map[] map[]}  <nil> <nil>} map[] <nil> <nil> false <nil> {map[] map[]} nil  [] []}']

To try to investigate the problem I went on to install the pg-operator with the help from @the-redback 

@the-redback instructed me to install the pg-operator using

    curl -fsSL https://raw.githubusercontent.com/kubedb/postgres/dev8.0/hack/deploy/setup.sh | bash

After that successfully started I tried to add the quickstart example of postgres again:

    apiVersion: kubedb.com/v1alpha1
    kind: Postgres
    metadata:
      name: quick-postgres
      namespace: limbo-review
    spec:
      version: "9.6"
      doNotPause: true
      storage:
        storageClassName: portworx-db-delete
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 50Gi

which lead to the following logs from the pg-operator:

    I0612 12:12:38.362473       1 wrap.go:42] GET /apis/mutators.kubedb.com/v1alpha1: (11.043882ms) 200 [[hyperkube/v1.9.7 (linux/amd64) kubernetes/dd5e1a2/system:serviceaccount:kube-system:generic-garbage-collector] 10.233.66.0:44348]
    I0612 12:12:38.403400       1 wrap.go:42] GET /apis/validators.kubedb.com/v1alpha1: (2.629301ms) 200 [[hyperkube/v1.9.7 (linux/amd64) kubernetes/dd5e1a2/system:serviceaccount:kube-system:generic-garbage-collector] 10.233.66.0:44348]
    I0612 12:12:40.970899       1 wrap.go:42] POST /apis/mutators.kubedb.com/v1alpha1/postgreses: (73.269255ms) 201 [[Go-http-client/2.0] 10.233.64.1:35698]
    I0612 12:12:40.989284       1 wrap.go:42] POST /apis/validators.kubedb.com/v1alpha1/postgreses: (14.231218ms) 201 [[Go-http-client/2.0] 10.233.64.1:35698]
    I0612 12:12:41.004297       1 postgres.go:59] Patching Postgres limbo-review/quick-postgres with {"metadata":{"finalizers":["kubedb.com"]}}.
    E0612 12:12:41.009143       1 worker.go:76] Failed to process key limbo-review/quick-postgres. Reason: Internal error occurred: failed calling admission webhook "postgres.mutators.kubedb.com": Unauthorized
    I0612 12:12:41.009913       1 worker.go:80] Error syncing key limbo-review/quick-postgres: Internal error occurred: failed calling admission webhook "postgres.mutators.kubedb.com": Unauthorized
    I0612 12:12:41.015730       1 postgres.go:59] Patching Postgres limbo-review/quick-postgres with {"metadata":{"finalizers":["kubedb.com"]}}.
    E0612 12:12:41.167239       1 worker.go:76] Failed to process key limbo-review/quick-postgres. Reason: Internal error occurred: failed calling admission webhook "postgres.mutators.kubedb.com": Unauthorized
    I0612 12:12:41.167295       1 worker.go:80] Error syncing key limbo-review/quick-postgres: Internal error occurred: failed calling admission webhook "postgres.mutators.kubedb.com": Unauthorized
    I0612 12:12:41.178088       1 postgres.go:59] Patching Postgres limbo-review/quick-postgres with {"metadata":{"finalizers":["kubedb.com"]}}.
    E0612 12:12:41.571502       1 worker.go:76] Failed to process key limbo-review/quick-postgres. Reason: Internal error occurred: failed calling admission webhook "postgres.mutators.kubedb.com": Unauthorized
    I0612 12:12:41.571565       1 worker.go:80] Error syncing key limbo-review/quick-postgres: Internal error occurred: failed calling admission webhook "postgres.mutators.kubedb.com": Unauthorized
    I0612 12:12:41.592700       1 postgres.go:59] Patching Postgres limbo-review/quick-postgres with {"metadata":{"finalizers":["kubedb.com"]}}.
    E0612 12:12:42.101809       1 worker.go:76] Failed to process key limbo-review/quick-postgres. Reason: Internal error occurred: failed calling admission webhook "postgres.mutators.kubedb.com": Unauthorized
    I0612 12:12:42.101858       1 worker.go:80] Error syncing key limbo-review/quick-postgres: Internal error occurred: failed calling admission webhook "postgres.mutators.kubedb.com": Unauthorized
    I0612 12:12:42.142783       1 postgres.go:59] Patching Postgres limbo-review/quick-postgres with {"metadata":{"finalizers":["kubedb.com"]}}.
    E0612 12:12:42.526942       1 worker.go:76] Failed to process key limbo-review/quick-postgres. Reason: Internal error occurred: failed calling admission webhook "postgres.mutators.kubedb.com": Unauthorized
    I0612 12:12:42.526987       1 worker.go:80] Error syncing key limbo-review/quick-postgres: Internal error occurred: failed calling admission webhook "postgres.mutators.kubedb.com": Unauthorized
    I0612 12:12:42.607987       1 postgres.go:59] Patching Postgres limbo-review/quick-postgres with {"metadata":{"finalizers":["kubedb.com"]}}.
    E0612 12:12:42.872438       1 worker.go:76] Failed to process key limbo-review/quick-postgres. Reason: Internal error occurred: failed calling admission webhook "postgres.mutators.kubedb.com": Unauthorized
    E0612 12:12:42.872486       1 worker.go:90] Internal error occurred: failed calling admission webhook "postgres.mutators.kubedb.com": Unauthorized
    I0612 12:12:42.872499       1 worker.go:91] Dropping key "limbo-review/quick-postgres" out of the queue: Internal error occurred: failed calling admission webhook "postgres.mutators.kubedb.com": Unauthorized
    I0612 12:12:42.874443       1 wrap.go:42] GET /healthz: (3.77

From here I don't know how to get on with the issue since I'm not sure why the admission webhooks are getting an Unauthorized back:

    failed calling admission webhook "postgres.mutators.kubedb.com": Unauthorized

**Comment by tamalsaha** [comment]
This was a Kubernetes bug fixed in 1.9.9 or 1.10.x

https://gist.github.com/tamalsaha/78b772f6f0a28d7725221e76b3e48611
