### ISSUE TITLE
Support Custom configuration for Elasticsearch cluster

### ISSUE THREAD

**Issue by aerokite** [kubedb/project#193]
I want to use KubeDB in a production system. But I didn't find a way to provide custom configuration. 

When I will use topology setup, I may need to provide separate configuration for client and data nodes. 

Are you going to add these features soon?

**Comment by tamalsaha** [comment]
What do you have in mind? And example will help? We are working on adding it to the Postgres. The general idea is that user provides a `VolumeSource` that we mount in the StatefulSet and then use that config.
