### ISSUE TITLE
[ElasticSearch] ES_JAVA_OPT based on request not limit values

### ISSUE THREAD

**Issue by stormmore** [kubedb/project#197]
Souldn't the Xmx value be based on the limit and not the request value?

I updated my ES cluster to use 4GB from 1GB and it didn't update the ES_JAVA_OPTS values as I would have expected until I set the request at the same level. I would actually have expected the request value be used for Xms and the llmit value be use to set the Xmx one.

**Comment by the-redback** [comment]
We worked on an issue https://github.com/kubedb/project/issues/163 recently, where Users will be able to provide their own `env`, and these Env will overwrite the initial Envs of statefulsets (merged in master, will be added in next release). 

I guess, that would be a better way to provide `ES_JAVA_OPTS`.

Heap size as 80% of request resource is just a safe configuaration.  For production setup, using EnvList to provide `ES_JAVA_OPTS` is better.

**Comment by hossainemruz** [comment]
In 0.9.x it is configurable through `spec.podTemplate.spec.env`.
