### ISSUE TITLE
namespace stuck on deleting when kubedb object is inside

### ISSUE THREAD

**Issue by ArchiFleKs** [kubedb/project#199]
Hi, 

Kube version : 1.9.9
KubeDB version : 0.8.0

When trying to delete a namesapce it get stuck on deleting, after a while I checked resources and I saw that my kubedb object (a mongodb) was not deleted by the cascade deletion.

The namespace is stuck on terminating because mongo was not delete, when I tried to delete it manually, the kube-db operator cannot create the dormant database because the namespace is in terminating state so it is kind of stuck into a loop right now, is there a way to force delete and bypass the dormant database ? 

I think the issue is not present with other component using CRD like cert-manager etc becaue they do not try to create another object on deletion. 

When the namespace is delete, the state change from Active to Terminating and new object cannot be created inside, so if the state change before kubedb resource is deleted the dormant database creation fails

**Comment by tamalsaha** [comment]
Fixed. We now add a namepsace webhook to block namespace deletion when DoNotDelete database exists.
