### ISSUE TITLE
Improve wal-g cloud provider support

### ISSUE THREAD

**Issue by tamalsaha** [kubedb/project#21]
_From @tamalsaha on November 22, 2017 17:10_

- [x] S3
- [x] GCS
- [x] Azure
- [x] Swift
- [ ] Local Volume (for bare metal)

_Copied from original issue: kubedb/operator#140_

**Comment by Dirbaio** [comment]
+1 to this. Wal-g just added support for GCS in wal-g/wal-g#161. It would be very nice to see this integrated in kubedb :)

**Comment by tamalsaha** [comment]
Dup https://github.com/kubedb/project/issues/446
