### ISSUE TITLE
Use ObservedGeneration in Status to keep track of last generation observed

### ISSUE THREAD

**Issue by the-redback** [kubedb/project#227]
- https://github.com/kubernetes/api/blob/495d099a8d378fbb811acf6eb8d0d932a45dd49c/apps/v1/types.go#L180

- Use the difference between meta.Generation and status.Observedgeneration as a `trigger`.

**Comment by tamalsaha** [comment]
Equals checks need to compare labels.

**Comment by tamalsaha** [comment]
Fixed.
