### ISSUE TITLE
Pass custom mysqldump arguments for scheduled backups

### ISSUE THREAD

**Issue by boxedcode** [kubedb/project#229]
Is it possible to pass custom mysqldump arguments when configuring scheduled backups? I've had a look at the documentation and did not see an obvious way to do it.

e.g. ```--default-character-set=utf8mb4```

Thanks..

**Comment by tamalsaha** [comment]
xref: https://github.com/kubedb/project/issues/221

**Comment by tamalsaha** [comment]
It is not possible today. But it should be possible.

**Comment by boxedcode** [comment]
OK cool, thanks

**Comment by tamalsaha** [comment]
We should keep the issue open until we have addressed it.

**Comment by tamalsaha** [comment]
https://github.com/kubedb/project/issues/238
