### ISSUE TITLE
SnapshotFailed   Failed to take snapshot. Reason: failed to get Elasticsearch indice

### ISSUE THREAD

**Issue by tamalsaha** [kubedb/project#230]
AWS Kops cluster. 1.10.5

https://kubernetes.slack.com/archives/C8149MREV/p1534328431000100

**Comment by the-redback** [comment]
Findings: 
- It's happening when `spec.enableSSL: false`

Todo: 
- [ ] Fix snapshot and other staffs for  `enableSSL: false`
- [ ] Improve err message
- [ ] Add test for both `topology` and `disabledSSL` for each `context` (Ex, snapshot, scheduler etc).
