### ISSUE TITLE
Redis HA

### ISSUE THREAD

**Issue by tamalsaha** [kubedb/project#232]
xref: https://github.com/kubedb/project/issues/44

- https://alex.dzyoba.com/blog/redis-ha/
- https://alex.dzyoba.com/blog/redis-cluster/
---
- https://redislabs.com/redis-features/high-availability
- https://redis.io/topics/cluster-tutorial

**Comment by shudipta** [comment]
Resources:
- https://redislabs.com/redis-features/high-availability
- https://redislabs.com/redis-features/redis-cluster


**example redis.conf for redis cluster:**
```
port 7000
cluster-enabled yes
cluster-config-file nodes.conf
cluster-node-timeout 5000
appendonly yes
```

**Comment by tamalsaha** [comment]
Reset node ip
https://sanderp.nl/running-redis-cluster-on-kubernetes-e451bda76cad

**Comment by tamalsaha** [comment]
Done
