### ISSUE TITLE
Document that requests is used for storage resources

### ISSUE THREAD

**Issue by tamalsaha** [kubedb/project#235]
`requests` field is the one that is used for storage. `limits` is not used for storage. In other way to put this, PVC/PV does not auto resize. So, `requests` field is the size you get for storage.

https://kubernetes.io/docs/concepts/storage/dynamic-provisioning/#using-dynamic-provisioning

https://kubernetes.slack.com/archives/C8149MREV/p1534481225000100

**Comment by the-redback** [comment]
- [ ] Postgres
- [ ] Elasticsearch
- [ ] MongoDB
- [ ] MySQL
- [ ] Redis
