### ISSUE TITLE
Service annotation 'tolerate-unready-endpoints' is deprecated

### ISSUE THREAD

**Issue by the-redback** [kubedb/project#242]
Service annotation `"service.alpha.kubernetes.io/tolerate-unready-endpoints": "true"` is deprecated. 
use `Service.spec.publishNotReadyAddresses: true`
ref: https://github.com/kubernetes/kubernetes/pull/63742

In code, needs to change, 
- mongodb: https://github.com/kubedb/mongodb/pull/48/files#diff-7e7819b35fe45d57d7c629853eb8e009R189
- etcd: https://github.com/kubedb/etcd/blob/4a60683ff1d8f7f908b288d6cc1afb1eb181cb60/pkg/controller/service.go#L15

**Comment by tamalsaha** [comment]
- [ ] What is the oldest version of K8s that supports the spec field.

**Comment by ryancastle** [comment]
Seems the spec field has been supported since Kubernetes 1.11

https://github.com/kubernetes/kubernetes/pull/63742

**Comment by tamalsaha** [comment]
KubeDB generated/managed services set `spec.PublishNotReadyAddresses = true` for some time.
