### ISSUE TITLE
Do not use fixed db user in Exporter

### ISSUE THREAD

**Issue by hossainemruz** [kubedb/project#252]
Currently KubeDB uses fixed DB username for some databases in exporter.
For Example,
PostgreSQL:
https://github.com/kubedb/operator/blob/2550b7722fd317f6e275bd20ac301167a11e5a04/pkg/exporter/exporter_handler.go#L239
Elasticsearch:
https://github.com/kubedb/operator/blob/2550b7722fd317f6e275bd20ac301167a11e5a04/pkg/exporter/exporter_handler.go#L131

If user uses custom db user then exporter might not work.

**Comment by tamalsaha** [comment]
https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#use-configmap-defined-environment-variables-in-pod-commands

**Comment by tamalsaha** [comment]
Postgres: 
https://github.com/wrouesnel/postgres_exporter/blob/master/cmd/postgres_exporter/postgres_exporter.go#L1073
