### ISSUE TITLE
When using nfs as PV provisioner, error on chown

### ISSUE THREAD

**Issue by PeterGrace** [kubedb/project#259]
Hi, I was trying to kick the tires on kubedb but I noticed that the postgres container was going into CrashLoopBackOff.  

I use the nfs-client provisioner as [provided by the external-storage repository](https://github.com/kubernetes-incubator/external-storage/tree/master/nfs-client).

Looking at the logs, it appears that the entrypoint script is trying to chown /var/pv, which I do not think will work in an nfs-mount scenario, as the /var/pv mountpoint is mounted and managed by the host, rather than kubernetes having a raw block device to work with internally.

A possible workaround might be to create a `data` folder underneath of /var/pv,  and using that, which the container would have control over changing the ownership and modes of.

If anyone has any other suggestions, please feel free to share them.

```
$ kubectl logs staging-0
I0902 14:36:03.220913       1 logs.go:19] FLAG: --alsologtostderr="false"
I0902 14:36:03.222085       1 logs.go:19] FLAG: --enable-analytics="true"
I0902 14:36:03.222184       1 logs.go:19] FLAG: --help="false"
I0902 14:36:03.222462       1 logs.go:19] FLAG: --log_backtrace_at=":0"
I0902 14:36:03.222533       1 logs.go:19] FLAG: --log_dir=""
I0902 14:36:03.222544       1 logs.go:19] FLAG: --logtostderr="false"
I0902 14:36:03.222549       1 logs.go:19] FLAG: --stderrthreshold="0"
I0902 14:36:03.222555       1 logs.go:19] FLAG: --v="0"
I0902 14:36:03.222561       1 logs.go:19] FLAG: --vmodule=""
I0902 14:36:03.403576       1 logs.go:19] chown /var/pv: operation not permitted
```

**Comment by PeterGrace** [comment]
This actually wound up being an issue with my nfs server -- the nfs mount was created with 000 permissions; once I figured it out, nfs started working just fine.  I'm leaving this here in case anyone else stumbles on this issue.

**Comment by Vlaoff** [comment]
Could you describe what you dit to solve this problem ?

**Comment by PeterGrace** [comment]
@Vlaoff, the problem was at my nfs server (synology), not at kubernetes.  I found that the filesystem itself on the synology had no permissions set (so user, group, other were all ---) once I set the directory with write permissions, the problem was solved.  If you're having nfs permission issues as well, you may also want to consider whether you are mounting with squash enabled or disabled.  squashing causes the nfs server to store all of the files with the same user id, which can sometimes cause docker containers with alternate uid's defined to have issues when they try to re-access a file they've created.
