### ISSUE TITLE
Feature request - HA Postgres cluster

### ISSUE THREAD

**Issue by tamalsaha** [kubedb/project#26]
_From @tamalsaha on November 19, 2017 5:5_

_From @rimusz on October 4, 2017 12:21_

HA Postgres cluster support please :)

_Copied from original issue: k8sdb/cli#120_

_Copied from original issue: kubedb/operator#131_

**Comment by SEJeff** [comment]
Consider looking at [stolon](https://github.com/sorintlab/stolon) which appears to be the state of the art "How do I run Postgres on kubernetes" solution currently.

**Comment by aerokite** [comment]
KubeDB Postgres supports HA cluster with asynchronous replication.
