### ISSUE TITLE
Snapshot cannot be removed for `hostPath` backend

### ISSUE THREAD

**Issue by zhenhuadong** [kubedb/project#261]
~/demo$ kubedb delete snap/local-snapshot -n demo
snapshot.kubedb.com "local-snapshot" deleted
~/demo$ kubedb get all -n demo
NAME                  DATABASE          STATUS    AGE
snap/local-snapshot   pg/hot-postgres   Failed    1h

~/demo$ cat local-snapshot.yaml
apiVersion: kubedb.com/v1alpha1
kind: Snapshot
metadata:
  name: local-snapshot
  namespace: demo
  labels:
    kubedb.com/kind: Postgres
spec:
  databaseName: hot-postgres
  local:
    path: /repo
    volumeSource:
      emptyDir: {}
  resources:
    requests:
      memory: "64Mi"
      cpu: "250m"
    limits:
      memory: "128Mi"
      cpu: "500m"

~/demo$ kubedb describe snap/local-snapshot -n demo
Name:                   local-snapshot
Namespace:              demo
CreationTimestamp:      Tue, 04 Sep 2018 10:27:55 +0200
CompletionTimestamp:    Tue, 04 Sep 2018 10:27:55 +0200
Labels:                 kubedb.com/kind=Postgres
                        kubedb.com/name=hot-postgres
                        snapshot.kubedb.com/status=Running
Status:                 Failed
Reason:                 One Snapshot is already Running
Storage:
  <unknown>
    Type:       Local
    path:

No events.

**Comment by hossainemruz** [comment]
@zhenhuadong can you show output of following command?
```
$ kubedb get snap/local-snapshot -n demo -o yaml
```
Please use following format while post output so it does preserve indentation.
\```
\<your output here\>
\```

**Comment by zhenhuadong** [comment]
@hossainemruz  i found the issue is still exist even the snapshot sucessful.

$ kubedb get snap/local-snapshot -n demo -o yaml
'''
apiVersion: kubedb.com/v1alpha1
kind: Snapshot
metadata:
  clusterName: ""
  creationTimestamp: 2018-09-04T10:22:12Z
  deletionGracePeriodSeconds: 0
  deletionTimestamp: 2018-09-05T01:08:56Z
  finalizers:
  - kubedb.com
  generation: 2
  labels:
    kubedb.com/kind: Postgres
    kubedb.com/name: hot-postgres
  name: local-snapshot
  namespace: demo
  resourceVersion: "112342"
  selfLink: /apis/kubedb.com/v1alpha1/namespaces/demo/snapshots/local-snapshot
  uid: 631e7016-b02c-11e8-8fcb-005056075466
spec:
  databaseName: hot-postgres
  local:
    mountPath: /repo
    volumeSource:
      hostPath:
        path: /repo
        type: Directory
  resources:
    limits:
      cpu: 500m
      memory: 128Mi
    requests:
      cpu: 250m
      memory: 64Mi
status:
  completionTime: 2018-09-04T10:22:21Z
  phase: Succeeded
  startTime: 2018-09-04T10:22:12Z

'''

**Comment by hossainemruz** [comment]
@zhenhuadong the reason behind Snapshot still exist is the finalizer in Snapshot metadata,
```
finalizers:
  - kubedb.com
```
KubeDB operator should remove this finalizer automatically when you perform delete operation. Somehow, the operator is failing to remove it. Can you see any error in KubeDB operator log?

However, you can manually remove the finalizer. 
```
$ kubedb edit snap/local-snapshot -n demo
```

then remove 
```
finalizers:
  - kubedb.com
```

**Comment by zhenhuadong** [comment]
the snapshot can be removed follow your tips. 
error logs in operator when i try to remove snapshot
```
E0905 05:27:38.114188       1 workqueue.go:39] [stat /repo: no such file or directory]
E0905 05:27:38.114807       1 worker.go:76] Failed to process key demo/local-snapshot. Reason: stat /repo: no such file or directory
I0905 05:27:38.114819       1 worker.go:80] Error syncing key demo/local-snapshot: stat /repo: no such file or directory
E0905 05:27:38.121469       1 workqueue.go:39] [stat /repo: no such file or directory]
E0905 05:27:38.121483       1 worker.go:76] Failed to process key demo/local-snapshot. Reason: stat /repo: no such file or directory
I0905 05:27:38.121488       1 worker.go:80] Error syncing key demo/local-snapshot: stat /repo: no such file or directory
E0905 05:27:38.132976       1 workqueue.go:39] [stat /repo: no such file or directory]
E0905 05:27:38.132999       1 worker.go:76] Failed to process key demo/local-snapshot. Reason: stat /repo: no such file or directory
I0905 05:27:38.133004       1 worker.go:80] Error syncing key demo/local-snapshot: stat /repo: no such file or directory
E0905 05:27:38.154281       1 workqueue.go:39] [stat /repo: no such file or directory]
E0905 05:27:38.154298       1 worker.go:76] Failed to process key demo/local-snapshot. Reason: stat /repo: no such file or directory
I0905 05:27:38.154304       1 worker.go:80] Error syncing key demo/local-snapshot: stat /repo: no such file or directory
E0905 05:27:38.195920       1 workqueue.go:39] [stat /repo: no such file or directory]
E0905 05:27:38.195940       1 worker.go:76] Failed to process key demo/local-snapshot. Reason: stat /repo: no such file or directory
I0905 05:27:38.195947       1 worker.go:80] Error syncing key demo/local-snapshot: stat /repo: no such file or directory
E0905 05:27:38.278735       1 workqueue.go:39] [stat /repo: no such file or directory]
E0905 05:27:38.278822       1 worker.go:76] Failed to process key demo/local-snapshot. Reason: stat /repo: no such file or directory
E0905 05:27:38.278839       1 worker.go:90] stat /repo: no such file or directory
I0905 05:27:38.278846       1 worker.go:91] Dropping key "demo/local-snapshot" out of the queue: stat /repo: no such file or directory
I0905 05:27:43.126278       1 wrap.go:42] GET /apis/mutators.kubedb.com/v1alpha1: (1.250616ms) 200 [[kube-controller-manager/v1.10.0 (linux/amd64) kubernetes/fc32d2f/system:serviceaccount:kube-system:resourcequota-controller] 10.210.125.164:40612]
```

**Comment by hossainemruz** [comment]
@zhenhuadong we have found the root cause.

When you delete Snapshot, KubeDB operator delete respective data from backend. If you are using `hostPath` volume as backend, KubeDB will fail to remove the data. This happen because KubeDB operator does not have access to the `hostPath` volume as it is not mounted in operator pod. So, this operation will return error and operator will not remove `finalizer` from the Snapshot. As a result, Snapshot can't be deleted.

**Workaround:**
Remove the finalizer manually.
```
$ kubedb edit snap/local-snapshot -n demo
```
then remove
```
finalizers:
  - kubedb.com
```

**Fix:**
Don't try to remove Snapshot data when `local` backend is used and update documentation accordingly.

**Task list:**
Fix this issue in:
- [ ] Elasticsearch
- [ ] Memcached
- [ ] MongoDB
- [ ] MySQL
- [ ] PostgreSQL
- [ ] Redis
- [ ] Etcd

- [ ] Update documentation
