### ISSUE TITLE
Migration plan for 0.8.0 to 0.9.0

### ISSUE THREAD

**Issue by tamalsaha** [kubedb/project#268]
Conversation on Slack http://slack.kubernetes.io

- https://kubernetes.slack.com/archives/C8149MREV/p1536171512000100

**Comment by tamalsaha** [comment]
I have summarized and rephrased my conversation with @stormmore below:

We are in the camp that the operator should be able to do an upgrade once it is told that it should upgrade without any further manual steps unless there is a problem. Say, for a 3 node ES cluster, once one replica is updated, the cluster should be verified ok, then another replica gets updated. Kinda like how `kops rolling-update` works - cordon, drain, terminate, start new, validate cluster (verifies that the new node can have pods scheduled), rinse and repeat. If validation fails, then kops stops so that it can be investigated and the cluster manually brought back in to a verifiable state.

The issue is operator currently don't have the capability and it will take time to implement this correctly. We don't want to block 0.9.0 for this.

So, the **plan** is:

Give users choice of using `RollingUpdate` (default) or `OnDelete`. Later, we add an option for operator managed `AutoUpdate` that will use appropriate approach to achieve the goal is first paragraph.

**Comment by tamalsaha** [comment]
Tags must not be reapplied for any docker images. Because, it is hard to guarantee that things will not break. Also, people using old version of operator, it will probably break if they use the modified image.

So, we will have say, ES `6.2.0` (for  0.8.0) and `6.2.0-v2` (for 0.9.0). Upgrade from `0.8.0` to `0.9.0` doesn't change things unless the user requests it (updating CRD spec), and it is documented that to get the latest feature you have to update to image tag `x.x.x-v2` to get those features. If they do make the choice to change the spec, then operator will perform a rolling update with the caveat that verification is done at the end of the rolling update.

**Comment by stormmore** [comment]
It is worth noting that, at least for ES, there is an end point that can be queried about the status of the indices

**Comment by tamalsaha** [comment]
The process is documented here from Postgres: https://github.com/kubedb/cli/blob/0.10.0/docs/guides/postgres/upgrade-manual.md

Please open new issues, if there are further issues.
