### ISSUE TITLE
Cleanup status from PVCTemplate

### ISSUE THREAD

**Issue by tamalsaha** [kubedb/project#269]
https://kubernetes.slack.com/archives/C8149MREV/p1536172125000100

**Comment by tamalsaha** [comment]
We should cleanup any status of VolumeClaimTemplates in crd spec.

**Comment by the-redback** [comment]
Is it possible to remove PVCTemplate status from statefulset? I tried editing sts spec but the PVCTemplate status comes back.

**Comment by the-redback** [comment]
About DB CRD, we don't have status part. Only `PersistentVolumeClaimSpec` is there in spec. https://github.com/kubedb/apimachinery/blob/7d6ac75d29a6f7c7adfec09c056043c913807c01/apis/kubedb/v1alpha1/elasticsearch_types.go#L57
