### ISSUE TITLE
Add ability to set schedulerName in CRDs

### ISSUE THREAD

**Issue by ssboisen** [kubedb/project#277]
In order to run storage hyper-converged (co-locate compute and storage on same machine) it's necessary to set the schedulerName field in order to use a custom scheduler like [stork](https://github.com/libopenstorage/stork) that takes replica placement into consideration. 

However it doesn't seem like kubedb exposes this field in its CRDs, is this correct or did I miss something?

**Comment by tamalsaha** [comment]
You can set scheduler name in next release via `spec.podTemplate.schedulerName`.

-https://github.com/kubedb/apimachinery/blob/389e0d09df92218ff79fcbf1010deda9b0d36390/apis/kubedb/v1alpha1/elasticsearch_types.go#L79
- https://github.com/kubedb/apimachinery/blob/389e0d09df92218ff79fcbf1010deda9b0d36390/vendor/kmodules.xyz/offshoot-api/api/v1/types.go#L64

**Comment by ssboisen** [comment]
wonderful @tamalsaha - thank you for the very quick response!

**Comment by tamalsaha** [comment]
My pleasure!
