### ISSUE TITLE
Tracking: Use suffix for updated DBImage & Stop working for deprecated *Versions

### ISSUE THREAD

**Issue by hossainemruz** [kubedb/project#279]
Databases:
- [x] Elasticsearch
- [x] MySQL
- [x] MongoDB
- [x] PostgreSQL
- [x] Redis
- [x] Memcached

**Comment by the-redback** [comment]
xref: kubedb/project#182

**Comment by the-redback** [comment]
xref: kubedb/project#268
xref: kubedb/project#270
