### ISSUE TITLE
error: unable to retrieve the complete list of server APIs: mutators.kubedb.com/v1alpha1:

### ISSUE THREAD

**Issue by obeyler** [kubedb/project#287]
```
kubectl api-resources  ## from kubernetes 1.11
see https://kubernetes.io/docs/reference/kubectl/cheatsheet/

error: unable to retrieve the complete list of server APIs: mutators.kubedb.com/v1alpha1: the server is currently unable to handle the request, validators.kubedb.com/v1alpha1: the server is currently unable to handle the request

```

**Comment by the-redback** [comment]
Was the `kubedb-operator` deployment deleted? The installation creates two ApiService.
The deployment needs to be running to make the api-resources available. 

https://github.com/kubedb/cli/blob/master/hack/deploy/operator.yaml#L103-L136

**Comment by tamalsaha** [comment]
@obeyler , my guess is that you installed the operator using Helm chart and then deleted the chart. Then ran the `kubectl apis-resources` command.

This has been fixed https://github.com/kubedb/cli/pull/282 

If you are still having this problem, run the following commands:
```
kubectl delete validatingwebhookconfigurations validators.kubedb.com
kubectl delete mutatingwebhookconfiguration mutators.kubedb.com
```
