### ISSUE TITLE
Remove kubedb resources on "helm del --purge xyz"

### ISSUE THREAD

**Issue by soosap** [kubedb/project#289]
Currently if I `$ helm del --purge xyz` on helm charts with kubedb resources I do not observe a full "purge" of all the chart resources. Instead, the kubedb resources remain untouched. I have to manually execute `$ kubectl delete pg abc-postgres` after deleting the helm chart.

If I decide to `helm del --purge xyz` then I am pretty certain at that point that I want the kubedb resources to go away as well. This is feature request asking to maintain the original behaviour of helm when integrating kubedb resources into helm charts.

**Comment by tamalsaha** [comment]
`helm del --purge xyz` is used to purge the operator, the KubeDB resource can't be deleted since these are not managed by the operator helm chart.
