### ISSUE TITLE
TLS handshake error

### ISSUE THREAD

**Issue by hossainemruz** [kubedb/project#291]
**From slack:**
Reported by 2 users.
```
I0925 08:58:30.278721       1 logs.go:19] http: TLS handshake error from 10.42.4.0:35520: remote error: tls: bad certificate
```
**KubeDB:** 0.9.0-beta.0
**Cluster:** AKS
**Kubernetes Version:** 1.11.2
**Install Process:** Helm

**Comment by bootc** [comment]
I'm one of the two users but I'm not using AKS, I'm using RKE (Rancher Kubernetes Engine). Also using K8s 1.11 (I upgraded from .2 to .3 but same issue).

**Comment by tamalsaha** [comment]
This is a case of https://github.com/kubernetes/kubernetes/issues/61879

**Comment by yujunz** [comment]
Read through the linked issue but still don't know how to resolve it. Could you please shed some light on it? @tamalsaha

**Comment by toonsevrin** [comment]
Same issue when installing through argocd.

**Comment by shalomcbouncex** [comment]
I have the same issue on GKE, just installed the last 0.12.0 version and experiencing the problem. I got multiple other operators working fine on the same cluster(with mutatingwebhooks, etc...) and they work fine - so I can't see how this might be a bug in the api server.

**Comment by shalomcbouncex** [comment]
The kubedb.sh script seems to install a working operator unlike the helm chart, the helm chart is missing the onessl tool which creates certificates and replaces parameters in the resources that are deployed to kubernetes. This concludes the helm chart is indeed broken.
