### ISSUE TITLE
support configurable listening port on postgres operator

### ISSUE THREAD

**Issue by zhenhuadong** [kubedb/project#300]
is it possible to use configurable port in kubedb postgres?

User may need non default port in some cases.

**Comment by tamalsaha** [comment]
It is possible in 0.9.0-beta.x

**Comment by zhenhuadong** [comment]
Thanks, I will try it.

**Comment by tamalsaha** [comment]
Sorry, I have misspoke. We are looking into this.

**Comment by tamalsaha** [comment]
@zhenhuadong , why do you need to use custom port?

If we allow you to change the port of the service used to expose Postgres StatefulSet, will that work for you?

**Comment by tamalsaha** [comment]
@zhenhuadong, wondering what you think about this?

**Comment by zhenhuadong** [comment]
Just come back from vacation. 
Yes, It works in some way. However, it is better if we allowed customer to configure the listening port.

**Comment by tamalsaha** [comment]
We have added support changing the service port via `spec.serviceTemplate.spec.ports`.

If you would like to contribute changing pod ports for any of the databases, we are happy to host that. Otherwise, we are going to leave it at this for now.
