### ISSUE TITLE
how to customize the postgres db image based on other OS?

### ISSUE THREAD

**Issue by kinkeylau** [kubedb/project#304]
how to customize the postgres db image based on other OS, like redhat?

**Comment by kinkeylau** [comment]
You mean I can build a docker image based on Redhat and replace the image in following PostgresVersion CRD?
------------------
  db:
    image: "{{ .Values.dockerRegistry }}/**postgres:10.2-v1**"
------------------

**Comment by tamalsaha** [comment]
Yes

**Comment by tamalsaha** [comment]
If you like to contribute your RedHat based images to the project, we will be happy to host them. You can find our Docker files in the `./hack/docker` folder in respective db's repo.

Eg: https://github.com/kubedb/postgres/tree/master/hack/docker

**Comment by kinkeylau** [comment]
What's included in image kubedb/postgres:10.2-v1, only alphine linux + postgres 10.2?

**Comment by tamalsaha** [comment]
This is documented here: https://github.com/kubedb/cli/blob/master/docs/guides/postgres/custom-versions/setup.md

@kinkeylau , if you have further questions, please reopen.
