### ISSUE TITLE
Don't use fixed username for backup & recovery job in MySQL

### ISSUE THREAD

**Issue by hossainemruz** [kubedb/project#318]
MySQL backup & recovery job uses fixed username `root`.
Ref:https://github.com/kubedb/mysql/blob/7bcfbc48dcff2c378f06387ee3e1f0eb7f0e47ef/pkg/controller/job.go#L74

If users use custom secret then backup will fail.
Ref: https://github.com/kubedb/project/issues/313

**Comment by tamalsaha** [comment]
Fixed
