### ISSUE TITLE
Introduce ephemeral storage for Snapshot

### ISSUE THREAD

**Issue by hossainemruz** [kubedb/project#328]
**Problem:**
Currently, backup job creates a pvc to store dump files temporarily. This causing issue for some users. Some cluster does not remove respective pv when a pvc is removed. Hence, each snapshot job creates a pv that need to be removed manually.

**Solution:**
We can provides a way for users to use ephemeral storage like `emptyDir` for backup job.

**Comment by the-redback** [comment]
- [ ] Elasticsearch
- [ ] Postgres
- [ ] MongoDB
- [ ] MySQL
