### ISSUE TITLE
[elasticsearch] Add support for AntiAffinity

### ISSUE THREAD

**Issue by ekarlso** [kubedb/project#334]
Could we get something like this for the topology roles in Elasticsearch ?
```  podTemplate:
    spec:
      affinity:
        podAntityAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
              matchExpressions:
              - key: kubedb.com/kind
                operator: In
                values:
                  - Postgres
              - key: kubedb.com/name
                operator: In
                values:
                  - my-db
```

**Comment by erik-stephens** [comment]
+1 and specifics for our use-case: we'd like to help guide how elasticsearch data pods get scheduled across racks/chassis/etc.  Being able to specify arbitrary anti-affinity rules is what we need - [this elasticsearch helm chart](https://github.com/helm/charts/blob/fac7381293598b21bf7e14d88ae8fd0d7021b22f/stable/elasticsearch/templates/data-statefulset.yaml#L35-L55) tried to abstract that to a simpler interface and all it did was make sure pods didn't get scheduled to same host which wasn't sufficient.

**Comment by tamalsaha** [comment]
Discussion Notes:

- https://github.com/kubedb/apimachinery/blob/722f0b216a672deab3b8e4fc91a08107722beb58/apis/kubedb/v1alpha1/mongodb_types.go#L221

- https://kubernetes.io/docs/concepts/configuration/assign-pod-node/

StatefulSet specific affinity

Resource (cpu & memory)
Storage
PDB

ENV
Afinity
Toleration / Node Selector

preferredZones: []

**Comment by tamalsaha** [comment]
Fixed in recent release.
