### ISSUE TITLE
Question: Plan for supporting upstream Snapshot CRDs

### ISSUE THREAD

**Issue by wozniakjan** [kubedb/project#337]
Hi, upstream now contains application and cloud-provider agnostic snapshot CRDs. Is there any plan reusing these upstream snapshot objects or are the kubedb controllers tightly coupled with the kubedb snapshot CRDs that these are required for the application specific behaviour? 

https://kubernetes.io/blog/2018/10/09/introducing-volume-snapshot-alpha-for-kubernetes/

**Comment by tamalsaha** [comment]
Is there any special support needed from KubeDB?

**Comment by tamalsaha** [comment]
Moved to https://github.com/appscode/stash/issues/751
