### ISSUE TITLE
How monitoring with exist prometheus?

### ISSUE THREAD

**Issue by chenyg0911** [kubedb/project#341]
I've run prometheus on k8s cluster. the promethues install with helm according coreos promethus operator instrument. 
`helm repo add coreos https://s3-eu-west-1.amazonaws.com/coreos-charts/stable/`
`helm install coreos/prometheus-operator --name prometheus-operator --namespace monitoring`
`helm install coreos/kube-prometheus --name kube-prometheus --namespace monitoring`

the promethus with grafana work fine.
But, when I try to use kubedb with the exist prometheus, according doc:
https://kubedb.com/docs/0.9.0-rc.0/guides/redis/monitoring/using-coreos-prometheus-operator/

I config the demo1.yaml prometheus like below:
```
  monitor:
    agent: prometheus.io/coreos-operator
    prometheus:
      namespace: monitoring
      labels:
        app: kubedb
      interval: 10s
      port: 56790
```
I get kubedb create the servicemonitor on monitoring namespace, but promethues can't discovery the new exporter. 
What's the problem?  Does I using the missing agent configration?

attach the generated monitoring/servicemonitor:
```
kubectl get servicemonitor kubedb-demo-redis-mon-prometheus -n monitoring -o yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  creationTimestamp: 2018-11-13T07:28:47Z
  generation: 1
  labels:
    app: kubedb
    monitoring.appscode.com/service: redis-mon-prometheus-stats.demo
  name: kubedb-demo-redis-mon-prometheus
  namespace: monitoring
  resourceVersion: "98934"
  selfLink: /apis/monitoring.coreos.com/v1/namespaces/monitoring/servicemonitors/kubedb-demo-redis-mon-prometheus
  uid: c26d98cc-e715-11e8-a69e-525400c042d5
spec:
  endpoints:
  - interval: 10s
    path: /metrics
    port: prom-http
    targetPort: 0
  namespaceSelector:
    matchNames:
    - demo
  selector:
    matchLabels:
      kubedb.com/kind: Redis
      kubedb.com/name: redis-mon-prometheus

```

**Comment by the-redback** [comment]
Hi @chenyg0911 ,

I recreated the issue. In your installation, the `kube-prometheus` object of Prometheus kind, contains a field called `serviceMonitorSelector`.

```yaml
~ $ kubectl get prometheus --all-namespaces
NAMESPACE    NAME              AGE
monitoring   kube-prometheus   1h

~ $ kubectl get prometheus -n monitoring kube-prometheus -o yaml
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  creationTimestamp: 2018-11-15T08:41:09Z
  generation: 1
  labels:
    app: prometheus
    chart: prometheus-0.0.51
    heritage: Tiller
    prometheus: kube-prometheus
    release: kube-prometheus
  name: kube-prometheus
  namespace: monitoring
  resourceVersion: "8087"
  selfLink: /apis/monitoring.coreos.com/v1/namespaces/monitoring/prometheuses/kube-prometheus
  uid: 32f32986-e8b2-11e8-9020-08002753361c
spec:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchLabels:
              app: prometheus
              prometheus: kube-prometheus
          topologyKey: kubernetes.io/hostname
        weight: 100
  alerting:
    alertmanagers:
    - name: kube-prometheus-alertmanager
      namespace: monitoring
      port: http
  baseImage: quay.io/prometheus/prometheus
  externalUrl: http://kube-prometheus.monitoring:9090
  imagePullSecrets: []
  logLevel: info
  paused: false
  replicas: 1
  resources: {}
  retention: 24h
  routePrefix: /
  ruleSelector:
    matchLabels:
      prometheus: kube-prometheus
  serviceAccountName: kube-prometheus
  serviceMonitorSelector:
    matchLabels:
      prometheus: kube-prometheus
  version: v2.2.1
```

In `serviceMonitorSelector` part, the `matchLabels` is set to `prometheus: kube-prometheus`. 
You need to specify this `prometheus: kube-prometheus` label in KubeDB monitoring instead of `app: kubedb`. 

So, the working spec of monitoring is:

```yaml
  monitor:
    agent: prometheus.io/coreos-operator
    prometheus:
      namespace: monitoring
      labels:
        prometheus: kube-prometheus
      interval: 10s
      port: 56790
```

This solved the problem for me.

**Comment by tamalsaha** [comment]
@the-redback , let's update our docs with this use-case.

**Comment by chenyg0911** [comment]
I've Solved it to add  new label follow by the article: [https://devops.college/prometheus-operator-how-to-monitor-an-external-service-3cb6ac8d5acb](https://devops.college/prometheus-operator-how-to-monitor-an-external-service-3cb6ac8d5acb)
`prometheus: kube-prometheus`



Thanks @tamalsaha
