### ISSUE TITLE
Add field spec.podTemplate.spec.serviceAccountName to CRDs for more fine-grained security

### ISSUE THREAD

**Issue by ron1** [kubedb/project#343]
The StatefulSet serviceAccountName can be used to constrain the assignment of a securityContext. Rather than elevate privileges associated with the 'default' service account, it is better to assign a custom serviceAccountName for such a purpose. Add field spec.podTemplate.spec.serviceAccountName to CRDs to offer this more fine-grained security control. This is especially relevant for Elasticsearch which has an initContainer that requires "IPC_LOCK" and "SYS_RESOURCE" capabilities

**Comment by voidengineer** [comment]
Now that https://github.com/kubedb/project/issues/390 is done, this one would be a great next step!

**Comment by tamalsaha** [comment]
@voidengineer , we already create a separate service account for each database object with the PSP related changes. https://github.com/kubedb/elasticsearch/blob/master/pkg/controller/rbac.go#L79

Is there anything else to do here?

**Comment by tamalsaha** [comment]
Fixed!

**Comment by voidengineer** [comment]
This one would allow to reference an already existing service account instead of creating a new one for each db object. This way we do not need to write a new RoleBinding (ServiceAccount -> PSP) for each created db.

**Comment by tamalsaha** [comment]
`This way we do not need to write a new RoleBinding (ServiceAccount -> PSP) for each created db.` - Why are you hesitant to create a new RoleBinding for each db? We have tried to keep things separate so that clean up after deleting database is simple.

**Comment by tamalsaha** [comment]
Done.
