### ISSUE TITLE
enableAnlytics / logLevel flags not passed on to databases

### ISSUE THREAD

**Issue by rwos** [kubedb/project#345]
I'm using the helm charts (0.9.0-rc.0), and set my values to include
```
logLevel: 5
enableAnalytics: false
```

The kubedb-operator starts up using these, as expected:
```
...
I1114 17:55:01.877898       1 logs.go:19] FLAG: --enable-analytics="false" 
...
I1114 17:55:01.880528       1 logs.go:19] FLAG: --v="5"
...
```

However, when I start a postgres (for example), it still starts up with
```
...
I1115 13:14:24.981453       1 logs.go:19] FLAG: --enable-analytics="true"
...
I1115 13:14:24.982462       1 logs.go:19] FLAG: --v="0"
...
```

I would also be okay with setting this manually in the CRD, but I can't figure out how (`spec.podTemplate.spec.args` for example doesn't seem to end up anywhere).

**Comment by the-redback** [comment]
Can you also provide the `kubedb-operator` Deployment yaml?

**Comment by rwos** [comment]
That was a quick fix, thanks! 👍
