### ISSUE TITLE
Why does the Docker-Image for `kubedb/operator` contain Java?

### ISSUE THREAD

**Issue by voidengineer** [kubedb/project#346]
I looked at `hack/docker/setup.sh` and found, that you install openjdk8-jre-base, but after that, only the compiled `operator`-binary is installed/copied into the image.

The JRE seems to be unused, increases the image-size and (that is my main problem) makes the corporate proxy I have to use reject the image layer.

**Comment by voidengineer** [comment]
I found the commit where you add OpenJDK (https://github.com/kubedb/operator/commit/e5f9c1892da6487442f0eb79e0c999ada4941264), but it also does not explain why it is needed.
You also add `openssl` which _is_ used in https://github.com/kubedb/operator/blob/master/hack/libbuild/libbuild.py#L100.

**Comment by tamalsaha** [comment]
We might be able to use something like https://github.com/pavel-v-chernykh/keystore-go to replace keytool. This is not a high priority for the current team. If you would like to contribute, you are very much welcome.

**Comment by tamalsaha** [comment]
Doc: https://www.digitalocean.com/community/tutorials/java-keytool-essentials-working-with-java-keystores
