### ISSUE TITLE
installing KubeDB operator into docker-for-desktop-cluster

### ISSUE THREAD

**Issue by MarcoMontel** [kubedb/project#347]
I am trying to install the KubeDB operator into my docker-for-desktop-cluster following your Installation Guide at 

https://kubedb.com/docs/0.9.0-rc.0/setup/install/

```
$ curl -fsSL https://raw.githubusercontent.com/kubedb/cli/0.9.0-rc.0/hack/deploy/kubedb.sh | bash
checking kubeconfig context
docker-for-desktop

Downloading onessl ...
checking whether extended apiserver feature is enabled

Admission webhooks can't be used when kube apiserver is accesible without verifying its TLS certificate (insecure-skip-tls-verify : true).
```

In order to modify the insecure-skip-tls-verify on my cluster on my MacOS machine I have to:

```
$ kubectl config set-cluster docker-for-desktop-cluster --insecure-skip-tls-verify=false
Cluster "docker-for-desktop-cluster" set.
```

But after kubernetes restart the parameter return to its initial value and I am unable to proceed in the installation of the KubeDB operator.

**Comment by cmoulliard** [comment]
Related issue #584

**Comment by tamalsaha** [comment]
This has been resolved.
