### ISSUE TITLE
EKS deployment controller log full of spurious errors

### ISSUE THREAD

**Issue by dmarkey** [kubedb/project#380]
Such as:

I1230 03:10:20.404516       1 logs.go:19] http: TLS handshake error from 10.0.0.1:53548: remote error: tls: bad certificate
I1230 03:10:21.629450       1 logs.go:19] http: TLS handshake error from 10.0.0.1:53570: remote error: tls: bad certificate
I1230 03:10:28.178117       1 logs.go:19] http: TLS handshake error from 10.0.0.1:53642: remote error: tls: bad certificate
I1230 03:10:29.177290       1 logs.go:19] http: TLS handshake error from 10.0.0.1:53652: remote error: tls: bad certificate
I1230 03:10:29.875661       1 logs.go:19] http: TLS handshake error from 10.0.0.1:40474: remote error: tls: bad certificate
I1230 03:10:29.878769       1 logs.go:19] http: TLS handshake error from 10.0.0.1:40476: remote error: tls: bad certificate
I1230 03:10:40.598381       1 logs.go:19] http: TLS handshake error from 10.0.0.1:40604: remote error: tls: bad certificate
I1230 03:10:41.598538       1 logs.go:19] http: TLS handshake error from 10.0.0.1:40610: remote error: tls: bad certificate
I1230 03:10:48.405674       1 logs.go:19] http: TLS handshake error from 10.0.0.1:53874: remote error: tls: bad certificate
I1230 03:10:48.502741       1 logs.go:19] http: TLS handshake error from 10.0.0.1:53878: remote error: tls: bad certificate
I1230 03:10:49.818310       1 logs.go:19] http: TLS handshake error from 10.0.0.1:53900: remote error: tls: bad certificate
I1230 03:10:49.822358       1 logs.go:19] http: TLS handshake error from 10.0.0.1:53904: remote error: tls: bad certificate
I1230 03:10:50.608710       1 logs.go:19] http: TLS handshake error from 10.0.0.1:53910: remote error: tls: bad certificate

Although it still seems to be working OK

**Comment by tamalsaha** [comment]
Did you reinstall the operator while the old operator pod was running?

**Comment by dmarkey** [comment]
Not that i'm aware of.. should I re-install?

**Comment by tamalsaha** [comment]
What if your cluster version? Also, what is your EKS version?
https://docs.aws.amazon.com/eks/latest/userguide/platform-versions.html

Are you using Helm or script based install?

**Comment by dmarkey** [comment]
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T21:04:45Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.5-eks-6bad6d", GitCommit:"6bad6d9c768dc0864dab48a11653aa53b5a47043", GitTreeState:"clean", BuildDate:"2018-12-06T23:13:14Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

EKS 1.11.5

This is a fresh cluster.

Script based install.

**Comment by tamalsaha** [comment]
Last week we fixed an issue where if you run the installer twice consecutively (without uninstalling in between), it will cause TLS handshake errors. We are going to cut a release next week.

To fix that issue, you can uninstall, wait for the operator pod to disappear and then reinstall the operator.

If that is not the same case in your case, then it is some other issue that we have not seen before. In that case, please tell us the steps you took so that we can reproduce them.

**Comment by dmarkey** [comment]
If I reinstall will it blank my running DBs?

**Comment by hossainemruz** [comment]
@dmarkey just delete the operator pod. It will be recreated and the problem should be gone.

**Comment by tamalsaha** [comment]
I agree that should also solve the problem. If not, let us know.

**Comment by dmarkey** [comment]
indeed it does, thanks!
