### ISSUE TITLE
create an mongodb on kubernetes cluster issue

### ISSUE THREAD

**Issue by prabath88** [kubedb/project#381]
When I'm creating a mongodb database on kubernetes cluster ,  I'm getting "timed out waiting for the condition" error.
kubedb describe mg -n demo mgo-quickstart

![image](https://user-images.githubusercontent.com/31723706/50557882-441e0780-0d0f-11e9-8713-2b747fb9289c.png)

could you please advise on this issue.

**Comment by the-redback** [comment]
```
kubectl get sts -n demo mgo-quickstart
kubectl describe sts -n demo mgo-quickstart
```

Also, can you share the log of kubedb operator?

**Comment by prabath88** [comment]
Please see the log . thanks 

`root@ip-172-31-17-194:~# kubectl get sts -n demo mgo-quickstart
NAME             READY   AGE
mgo-quickstart   0/1     10m
root@ip-172-31-17-194:~# kubectl describe sts -n demo mgo-quickstart
Name:               mgo-quickstart
Namespace:          demo
CreationTimestamp:  Mon, 31 Dec 2018 10:34:53 +0000
Selector:           kubedb.com/kind=MongoDB,kubedb.com/name=mgo-quickstart
Labels:             kubedb.com/kind=MongoDB
                    kubedb.com/name=mgo-quickstart
Annotations:        <none>
Replicas:           824639930880 desired | 1 total
Update Strategy:    RollingUpdate
Pods Status:        0 Running / 1 Waiting / 0 Succeeded / 0 Failed
Pod Template:
  Labels:  kubedb.com/kind=MongoDB
           kubedb.com/name=mgo-quickstart
  Init Containers:
   copy-config:
    Image:      busybox
    Port:       <none>
    Host Port:  <none>
    Command:
      sh
    Args:
      -c
      set -xe
                      if [ -f "/configdb-readonly/mongod.conf" ]; then
                        cp /configdb-readonly/mongod.conf /data/configdb/mongod.conf
                      else
                        touch /data/configdb/mongod.conf
                      fi

                      if [ -f "/keydir-readonly/key.txt" ]; then
                        cp /keydir-readonly/key.txt /data/configdb/key.txt
                        chmod 600 /data/configdb/key.txt
                      fi
    Environment:  <none>
    Mounts:
      /data/configdb from config (rw)
      /work-dir from workdir (rw)
  Containers:
   mongodb:
    Image:      kubedb/mongo:3.4-v1
    Port:       27017/TCP
    Host Port:  0/TCP
    Args:
      --dbpath=/data/db
      --auth
      --bind_ip=0.0.0.0
      --port=27017
    Liveness:   exec [mongo --eval db.adminCommand('ping')] delay=0s timeout=5s period=10s #success=1 #failure=3
    Readiness:  exec [mongo --eval db.adminCommand('ping')] delay=0s timeout=1s period=10s #success=1 #failure=3
    Environment:
      MONGO_INITDB_ROOT_USERNAME:  <set to the key 'username' in secret 'mgo-quickstart-auth'>  Optional: false
      MONGO_INITDB_ROOT_PASSWORD:  <set to the key 'password' in secret 'mgo-quickstart-auth'>  Optional: false
    Mounts:
      /data/configdb from config (rw)
      /data/db from datadir (rw)
  Volumes:
   workdir:
    Type:    EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
   config:
    Type:    EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
Volume Claims:
  Name:          datadir
  StorageClass:  standard
  Labels:        <none>
  Annotations:   volume.beta.kubernetes.io/storage-class=standard
  Capacity:      1Gi
  Access Modes:  [ReadWriteOnce]
Events:
  Type    Reason            Age   From                    Message
  ----    ------            ----  ----                    -------
  Normal  SuccessfulCreate  10m   statefulset-controller  create Claim datadir-mgo-quickstart-0 Pod mgo-quickstart-0 in StatefulSet mgo-quickstart success
  Normal  SuccessfulCreate  10m   statefulset-controller  create Pod mgo-quickstart-0 in StatefulSet mgo-quickstart successful`

**Comment by prabath88** [comment]
Thanks for helping .. Please find the logs 

root@ip-172-31-17-194:~# kubectl get sts -n demo mgo-quickstart
NAME             READY   AGE
mgo-quickstart   0/1     10m


------------------------------------------------
root@ip-172-31-17-194:~# kubectl describe sts -n demo mgo-quickstart
Name:               mgo-quickstart
Namespace:          demo
CreationTimestamp:  Mon, 31 Dec 2018 10:34:53 +0000
Selector:           kubedb.com/kind=MongoDB,kubedb.com/name=mgo-quickstart
Labels:             kubedb.com/kind=MongoDB
                    kubedb.com/name=mgo-quickstart
Annotations:        <none>
Replicas:           824639930880 desired | 1 total
Update Strategy:    RollingUpdate
Pods Status:        0 Running / 1 Waiting / 0 Succeeded / 0 Failed
Pod Template:
  Labels:  kubedb.com/kind=MongoDB
           kubedb.com/name=mgo-quickstart
  Init Containers:
   copy-config:
    Image:      busybox
    Port:       <none>
    Host Port:  <none>
    Command:
      sh
    Args:
      -c
      set -xe
                      if [ -f "/configdb-readonly/mongod.conf" ]; then
                        cp /configdb-readonly/mongod.conf /data/configdb/mongod.conf
                      else
                        touch /data/configdb/mongod.conf
                      fi

                      if [ -f "/keydir-readonly/key.txt" ]; then
                        cp /keydir-readonly/key.txt /data/configdb/key.txt
                        chmod 600 /data/configdb/key.txt
                      fi
    Environment:  <none>
    Mounts:
      /data/configdb from config (rw)
      /work-dir from workdir (rw)
  Containers:
   mongodb:
    Image:      kubedb/mongo:3.4-v1
    Port:       27017/TCP
    Host Port:  0/TCP
    Args:
      --dbpath=/data/db
      --auth
      --bind_ip=0.0.0.0
      --port=27017
    Liveness:   exec [mongo --eval db.adminCommand('ping')] delay=0s timeout=5s period=10s #success=1 #failure=3
    Readiness:  exec [mongo --eval db.adminCommand('ping')] delay=0s timeout=1s period=10s #success=1 #failure=3
    Environment:
      MONGO_INITDB_ROOT_USERNAME:  <set to the key 'username' in secret 'mgo-quickstart-auth'>  Optional: false
      MONGO_INITDB_ROOT_PASSWORD:  <set to the key 'password' in secret 'mgo-quickstart-auth'>  Optional: false
    Mounts:
      /data/configdb from config (rw)
      /data/db from datadir (rw)
  Volumes:
   workdir:
    Type:    EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
   config:
    Type:    EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
Volume Claims:
  Name:          datadir
  StorageClass:  standard
  Labels:        <none>
  Annotations:   volume.beta.kubernetes.io/storage-class=standard
  Capacity:      1Gi
  Access Modes:  [ReadWriteOnce]
Events:
  Type    Reason            Age   From                    Message
  ----    ------            ----  ----                    -------
  Normal  SuccessfulCreate  10m   statefulset-controller  create Claim datadir-mgo-quickstart-0 Pod mgo-quickstart-0 in StatefulSet mgo-quickstart success
  Normal  SuccessfulCreate  10m   statefulset-controller  create Pod mgo-quickstart-0 in StatefulSet mgo-quickstart successful
root@ip-172-31-17-194:~#

**Comment by the-redback** [comment]
Can you also see these output? 

```
kubectl get pods -n demo
kubectl describe pods -n demo mgo-quickstart-0
kubectl describe pods -n demo mgo-quickstart-1
kubectl describe pods -n demo mgo-quickstart-2
```

**Comment by prabath88** [comment]
`root@ip-172-31-17-194:~# kubectl get pods -n demo
NAME               READY   STATUS    RESTARTS   AGE
mgo-quickstart-0   0/1     Pending   0          25m`

============================================================
`kubectl describe pods -n demo mgo-quickstart-0
Name:               mgo-quickstart-0
Namespace:          demo
Priority:           0
PriorityClassName:  <none>
Node:               <none>
Labels:             controller-revision-hash=mgo-quickstart-5c57c55867
                    kubedb.com/kind=MongoDB
                    kubedb.com/name=mgo-quickstart
                    statefulset.kubernetes.io/pod-name=mgo-quickstart-0
Annotations:        <none>
Status:             Pending
IP:
Controlled By:      StatefulSet/mgo-quickstart
Init Containers:
  copy-config:
    Image:      busybox
    Port:       <none>
    Host Port:  <none>
    Command:
      sh
    Args:
      -c
      set -xe
                      if [ -f "/configdb-readonly/mongod.conf" ]; then
                        cp /configdb-readonly/mongod.conf /data/configdb/mongod.conf
                      else
                        touch /data/configdb/mongod.conf
                      fi

                      if [ -f "/keydir-readonly/key.txt" ]; then
                        cp /keydir-readonly/key.txt /data/configdb/key.txt
                        chmod 600 /data/configdb/key.txt
                      fi
    Environment:  <none>
    Mounts:
      /data/configdb from config (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-wbk6p (ro)
      /work-dir from workdir (rw)
Containers:
  mongodb:
    Image:      kubedb/mongo:3.4-v1
    Port:       27017/TCP
    Host Port:  0/TCP
    Args:
      --dbpath=/data/db
      --auth
      --bind_ip=0.0.0.0
      --port=27017
    Liveness:   exec [mongo --eval db.adminCommand('ping')] delay=0s timeout=5s period=10s #success=1 #failure=3
    Readiness:  exec [mongo --eval db.adminCommand('ping')] delay=0s timeout=1s period=10s #success=1 #failure=3
    Environment:
      MONGO_INITDB_ROOT_USERNAME:  <set to the key 'username' in secret 'mgo-quickstart-auth'>  Optional: false
      MONGO_INITDB_ROOT_PASSWORD:  <set to the key 'password' in secret 'mgo-quickstart-auth'>  Optional: false
    Mounts:
      /data/configdb from config (rw)
      /data/db from datadir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-wbk6p (ro)
Conditions:
  Type           Status
  PodScheduled   False
Volumes:
  datadir:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  datadir-mgo-quickstart-0
    ReadOnly:   false
  workdir:
    Type:    EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
  config:
    Type:    EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
  default-token-wbk6p:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-wbk6p
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason            Age                From               Message
  ----     ------            ----               ----               -------
  Warning  FailedScheduling  25m (x4 over 25m)  default-scheduler  pod has unbound immediate PersistentVolumeClaims`

=======================================================
root@ip-172-31-17-194:~# kubectl describe pods -n demo mgo-quickstart-1
Error from server (NotFound): pods "mgo-quickstart-1" not found
root@ip-172-31-17-194:~# kubectl describe pods -n demo mgo-quickstart-2
Error from server (NotFound): pods "mgo-quickstart-2" not found

**Comment by the-redback** [comment]
looks like issue with `pvc`. Can you share how you provision your cluster? Kubernetes version? Disk type? And also, output of following command:

``` 
kubectl get pvc -n demo
kubectl get storageclass -o yaml
```

**Comment by prabath88** [comment]
Actually I have test this in a aws . I am using aws ebs general purpose disk. in this case I'm using AWS AMI . (Kubernetes Sandbox Certified by Bitnami) single node cluster.  But I have face same issue with on other environment, created by using  single master cluster with kubeadm . In that cases i have used calico for the pod network. 

Please see the required output of above commands. 

```
root@ip-172-31-17-194:~# kubectl get pvc -n demo
NAME                       STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS   AGE
datadir-mgo-quickstart-0   Pending                                      standard       43m
root@ip-172-31-17-194:~# kubectl get storageclass -o yaml
apiVersion: v1
items:
- apiVersion: storage.k8s.io/v1
  kind: StorageClass
  metadata:
    annotations:
      storageclass.kubernetes.io/is-default-class: "true"
    creationTimestamp: "2018-12-31T08:46:57Z"
    name: fast-disks
    resourceVersion: "557"
    selfLink: /apis/storage.k8s.io/v1/storageclasses/fast-disks
    uid: a1569b61-0cd8-11e9-89a1-0214ed9256e6
  provisioner: kubernetes.io/no-provisioner
  reclaimPolicy: Delete
  volumeBindingMode: WaitForFirstConsumer
- apiVersion: storage.k8s.io/v1
  kind: StorageClass
  metadata:
    creationTimestamp: "2018-12-31T09:27:00Z"
    name: standard
    resourceVersion: "4241"
    selfLink: /apis/storage.k8s.io/v1/storageclasses/standard
    uid: 39f2cf41-0cde-11e9-89a1-0214ed9256e6
  mountOptions:
  - debug
  parameters:
    type: gp2
  provisioner: kubernetes.io/aws-ebs
  reclaimPolicy: Retain
  volumeBindingMode: Immediate
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""

```
