### ISSUE TITLE
ES Snapshot

### ISSUE THREAD

**Issue by endrec** [kubedb/project#382]
When kubedb creates a new job to take a snapshot from an ES cluster, it looks for `Elasticsearch.spec.storage` to determine if it should use a PV for temporary storage.

If `Elasticsearch.spec.topology` is set, `Elasticsearch.spec.storage` can not be used, so the snapshot will try to use `emptyDir` for temporary storage. 

It is very likely that the temporary storage will not fit on the node's local disk, so the snapshot pod will be evicted, and the snapshot will fail.

When `Elasticsearch.spec.topology` is set, the operator should use `Elasticsearch.spec.topology.data.storage` instead.

**Comment by tamalsaha** [comment]
https://kubernetes.slack.com/archives/C8149MREV/p1546439857095100

**Comment by tamalsaha** [comment]
https://gist.github.com/tamalsaha/73de0224c47a085d0a17df89412b80cf
