### ISSUE TITLE
`podVolumeClaimSpec` of Snapshot crd does not work when ephemeral storage is used for database

### ISSUE THREAD

**Issue by hossainemruz** [kubedb/project#389]
If database was created with Ephemeral storage, `podVolumeClaimSpec` of Snapshot crd does not work.

Reason:
If storage type of database crd is Ephemeral then `pvcSpec` is used to specify limit.
https://github.com/kubedb/postgres/blob/484926608cbf7fbf44deb4727196fbf742eb5292/pkg/controller/job.go#L310

**Comment by the-redback** [comment]
- [ ] Elasticsearch
- [ ] Postgres
- [ ] MongoDB
- [ ] MySQL
- [ ] Tests
