### ISSUE TITLE
Support for PSP-enabled clusters

### ISSUE THREAD

**Issue by hossainemruz** [kubedb/project#390]
KubeDB create a `serviceAccount` with same name as database crd for PostgreSQL only. But it does not do the same for other databases.

Ref: https://github.com/kubedb/postgres/blob/a697976a11a00283001823a0deed7eea0c8c5025/pkg/controller/statefulset.go#L127

Users need this serviceAccount for podSecurityPolicy.

Slack: https://kubernetes.slack.com/archives/C8149MREV/p1546870527128800?thread_ts=1546869727.128100&cid=C8149MREV

**Comment by tamalsaha** [comment]
This makes me nostalgic. I remember when removed DB instance specific service accounts, since we did not need to make any api calls to kube-apiserver. Now, we need to back for PSP. We should have this.

**Comment by the-redback** [comment]
- [ ] Elasticsearch
- [ ] MongoDB
- [ ] MySQL
- [ ] Redis
- [ ] Memcached

**Comment by tamalsaha** [comment]
Discussion: https://www.youtube.com/watch?v=XYA6-0bg0xg

**Comment by tamalsaha** [comment]
Should be fixed.

**Comment by tamalsaha** [comment]
Fixed in 0.11.0
