### ISSUE TITLE
Cannot create kubedb-operator in namespace due to priorityClass

### ISSUE THREAD

**Issue by dennisameling** [kubedb/project#395]
Kubernetes version: 1.11.5
Platform: AKS
RBAC enabled: yes

When running `curl -fsSL https://raw.githubusercontent.com/kubedb/cli/0.9.0/hack/deploy/kubedb.sh | bash -s -- -n kubedb` to install the kubedb-operator in namespace `kubedb`, the deployment fails with the following error:

`Error creating: pods "kubedb-operator-7db87b7f57-" is forbidden: pods with system-cluster-critical priorityClass is not permitted in kubedb namespace`

This is due to the fact that, like the error suggests, pods with the system-cluster-critical priorityClass are not permitted in other namespaces than the `kube-system` namespace.

Workaround is to install KubeDB in the `kube-system` namespace, which is the default.

**Comment by tamalsaha** [comment]
Fixed in https://github.com/kubedb/cli/pull/394
