### ISSUE TITLE
Error from server (Timeout): the server was unable to return a response in the time allotted, but may still be processing the request (delete namespaces test)

### ISSUE THREAD

**Issue by frouzbeh** [kubedb/project#397]
Hi, 

I have a test kubernetes cluster on three virtual machines which works fine. Recently, I started to deploy postgres using kubedb, but I've seen an issue after I installed kubedb operator and kubedb catalog.
Every time I installed those I get the following error for different commands (even for the commands that are independent of kubedb)
For example, I created a test namespace and wanted to delete it but I got:

`Error from server (Timeout): the server was unable to return a response in the time allotted, but may still be processing the request (delete namespaces test)`
Here is the resources that are attached to namespace "test":

```
kubectl get all -n test
NAME                                               VERSION   DB_IMAGE                        DEPRECATED   AGE
elasticsearchversion.catalog.kubedb.com/5.6        5.6       kubedb/elasticsearch:5.6        true         2h
elasticsearchversion.catalog.kubedb.com/5.6-v1     5.6       kubedb/elasticsearch:5.6-v1                  2h
elasticsearchversion.catalog.kubedb.com/5.6.4      5.6.4     kubedb/elasticsearch:5.6.4      true         2h
elasticsearchversion.catalog.kubedb.com/5.6.4-v1   5.6.4     kubedb/elasticsearch:5.6.4-v1                2h
elasticsearchversion.catalog.kubedb.com/6.2        6.2       kubedb/elasticsearch:6.2        true         2h
elasticsearchversion.catalog.kubedb.com/6.2-v1     6.2       kubedb/elasticsearch:6.2-v1                  2h
elasticsearchversion.catalog.kubedb.com/6.2.4      6.2.4     kubedb/elasticsearch:6.2.4      true         2h
elasticsearchversion.catalog.kubedb.com/6.2.4-v1   6.2.4     kubedb/elasticsearch:6.2.4-v1                2h
elasticsearchversion.catalog.kubedb.com/6.3        6.3       kubedb/elasticsearch:6.3        true         2h
elasticsearchversion.catalog.kubedb.com/6.3-v1     6.3       kubedb/elasticsearch:6.3-v1                  2h
elasticsearchversion.catalog.kubedb.com/6.3.0      6.3.0     kubedb/elasticsearch:6.3.0      true         2h
elasticsearchversion.catalog.kubedb.com/6.3.0-v1   6.3.0     kubedb/elasticsearch:6.3.0-v1                2h
elasticsearchversion.catalog.kubedb.com/6.4        6.4       kubedb/elasticsearch:6.4                     2h
elasticsearchversion.catalog.kubedb.com/6.4.0      6.4.0     kubedb/elasticsearch:6.4.0                   2h

NAME                                          VERSION   DB_IMAGE                   DEPRECATED   AGE
postgresversion.catalog.kubedb.com/10.2       10.2      kubedb/postgres:10.2       true         2h
postgresversion.catalog.kubedb.com/10.2-v1    10.2      kubedb/postgres:10.2-v2                 2h
postgresversion.catalog.kubedb.com/9.6        9.6       kubedb/postgres:9.6        true         2h
postgresversion.catalog.kubedb.com/9.6-v1     9.6       kubedb/postgres:9.6-v2                  2h
postgresversion.catalog.kubedb.com/9.6.7      9.6.7     kubedb/postgres:9.6.7      true         2h
postgresversion.catalog.kubedb.com/9.6.7-v1   9.6.7     kubedb/postgres:9.6.7-v2                2h

NAME                                    VERSION   DB_IMAGE              DEPRECATED   AGE
etcdversion.catalog.kubedb.com/3.2.13   3.2.13    kubedb/etcd:v3.2.13                2h

NAME                                       VERSION   DB_IMAGE              DEPRECATED   AGE
mongodbversion.catalog.kubedb.com/3.4      3.4       kubedb/mongo:3.4      true         2h
mongodbversion.catalog.kubedb.com/3.4-v1   3.4       kubedb/mongo:3.4-v1                2h
mongodbversion.catalog.kubedb.com/3.6      3.6       kubedb/mongo:3.6      true         2h
mongodbversion.catalog.kubedb.com/3.6-v1   3.6       kubedb/mongo:3.6-v1                2h

NAME                                     VERSION   DB_IMAGE              DEPRECATED   AGE
mysqlversion.catalog.kubedb.com/5        5         kubedb/mysql:5        true         2h
mysqlversion.catalog.kubedb.com/5-v1     5         kubedb/mysql:5-v1                  2h
mysqlversion.catalog.kubedb.com/5.7      5.7       kubedb/mysql:5.7      true         2h
mysqlversion.catalog.kubedb.com/5.7-v1   5.7       kubedb/mysql:5.7-v1                2h
mysqlversion.catalog.kubedb.com/8        8         kubedb/mysql:8        true         2h
mysqlversion.catalog.kubedb.com/8-v1     8         kubedb/mysql:8-v1                  2h
mysqlversion.catalog.kubedb.com/8.0      8.0       kubedb/mysql:8.0      true         2h
mysqlversion.catalog.kubedb.com/8.0-v1   8.0       kubedb/mysql:8.0-v1                2h

NAME                                       VERSION   DB_IMAGE                DEPRECATED   AGE
redisversion.catalog.kubedb.com/4          4         kubedb/redis:4          true         2h
redisversion.catalog.kubedb.com/4-v1       4         kubedb/redis:4-v1                    2h
redisversion.catalog.kubedb.com/4.0        4.0       kubedb/redis:4.0        true         2h
redisversion.catalog.kubedb.com/4.0-v1     4.0       kubedb/redis:4.0-v1                  2h
redisversion.catalog.kubedb.com/4.0.6      4.0.6     kubedb/redis:4.0.6      true         2h
redisversion.catalog.kubedb.com/4.0.6-v1   4.0.6     kubedb/redis:4.0.6-v1                2h

NAME                                           VERSION   DB_IMAGE                    DEPRECATED   AGE
memcachedversion.catalog.kubedb.com/1.5        1.5       kubedb/memcached:1.5        true         2h
memcachedversion.catalog.kubedb.com/1.5-v1     1.5       kubedb/memcached:1.5-v1                  2h
memcachedversion.catalog.kubedb.com/1.5.4      1.5.4     kubedb/memcached:1.5.4      true         2h
memcachedversion.catalog.kubedb.com/1.5.4-v1   1.5.4     kubedb/memcached:1.5.4-v1                2h

```
I can see these resources for all my namespaces and that's weird. After I delete those deployments everything goes back to normal and I can delete the namespace. 

Anybody knows what's the reason?

**Comment by the-redback** [comment]
Hi @frouzbeh , How did you install kubedb? Helm or bash script? Also, what is your kubernetes version? And, How you provision your cluster?

**Comment by frouzbeh** [comment]
Thanks, @the-redback
I used helm to install kubedb, and I have deployed my Kubernetes cluster using RKE (rancher Kubernetes Engine) on three virtual machines. 
In my case, I tried to install kubedb two times, and the second time I just created a test namespace with no resource after I installed kubedb. As you can see all the kubedb resources was shown in test namespace, and I think that's why it doesn't allow to delete that. 

Right now I'm working on another project, but I can recreate this and let you know later when I got a free time.

**Comment by antonu17** [comment]
Just faced the same problem. EKS 1.13.7, KubeDB 0.12.0, helm installer, kubedb-operator is installed into `kube-system` namespace. After kubedb is installed, all `kubectl delete namespace` calls fail with a timeout. As soon as kubedb operator chart is deleted, namespace deletion passes.
There are some log messages from kubedb-operator pod:
```
kubedb-operator-9ccd79d68-tvjzk operator E0830 20:18:02.866855       1 status.go:64] apiserver received an error that is not an metav1.Status: http2.StreamError{StreamID:0x2c9, Code:0x0, Cause:error(nil)}
kubedb-operator-9ccd79d68-tvjzk operator E0830 20:18:02.866909       1 writers.go:168] apiserver was unable to write a JSON response: http: Handler timeout
kubedb-operator-9ccd79d68-tvjzk operator E0830 20:18:02.867937       1 status.go:64] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"http: Handler timeout"}
kubedb-operator-9ccd79d68-tvjzk operator I0830 20:18:02.869059       1 trace.go:76] Trace[1201286137]: "Create /apis/validators.kubedb.com/v1alpha1/namespaces" (started: 2019-08-30 20:17:02.86670581 +0000 UTC m=+1275.720823740) (total time: 1m0.002325989s):
kubedb-operator-9ccd79d68-tvjzk operator Trace[1201286137]: [1m0.002325989s] [1m0.002325989s] END
```

**Comment by skad0Osh** [comment]
Having the same issue, I deployed kubedb operator to our kube cluster (v 1.15) but with validation webhook enabled on the operator, any attempt to create a postgres instance times out. Is there a way to find out why this is happening?
operator log shows:
1017 02:53:16.320838       1 status.go:64] apiserver received an error that is not an metav1.Status: http2.StreamError{StreamID:0x7, Code:0x8, Cause:error(nil)}
I1017 02:53:16.321233       1 trace.go:76] Trace[629458047]: "Create /apis/mutators.kubedb.com/v1alpha1/postgreses" (started: 2019-10-17 02:52:46.321671667 +0000 UTC m=+84.700306066) (total time: 29.999520351s):
Trace[629458047]: [29.999520351s] [29.999520351s] END

log of pod/kube-controller-manager

E1018 01:36:55.582060       1 resource_quota_controller.go:407] unable to retrieve the complete list of server APIs: mutators.kubedb.com/v1alpha1: the server is currently unable to handle the request
W1018 01:37:15.148979       1 garbagecollector.go:638] failed to discover some groups: map[mutators.kubedb.com/v1alpha1:the server is currently unable to handle the request]
E1018 01:37:26.434490       1 resource_quota_controller.go:407] unable to retrieve the complete list of server APIs: mutators.kubedb.com/v1alpha1: the server is currently unable to handle the request
W1018 01:37:48.351286       1 garbagecollector.go:638] failed to discover some groups: map[mutators.kubedb.com/v1alpha1:the server is currently unable to handle the request]
E1018 01:37:57.287011       1 resource_quota_controller.go:407] unable to retrieve the complete list of server APIs: mutators.kubedb.com/v1alpha1: the server is currently unable to handle the request

**Comment by Teingi** [comment]
Any progress? Same mistake

'''
I0204 07:55:33.009668       1 trace.go:81] apiserver received an error that is not an metav1.Status: http2.StreamError{StreamID:0x7, Code:0x8, Cause:error(nil)}

I0204 07:56:03.061355       1 trace.go:81] Trace[1101847029]: "Create /apis/mutators.kubedb.com/v1alpha1/mysqlmutators" (started: 2021-02-04 07:55:33.059012551 +0000 UTC m=+4607.275087482) (total time: 30.00231439s):

'''

**Comment by tamalsaha** [comment]
https://github.com/kubedb/installer/pull/266
