### ISSUE TITLE
How we can pass the directory of scripts to postgres and run the scripts later inside the container?

### ISSUE THREAD

**Issue by frouzbeh** [kubedb/project#398]
Hi, 

I was wondering if there is a solution to pass a directory of scripts (to create a database and import the data) into postgres, so we can see those scripts inside the container and run them? 
In the documents there is a solution to initialize postgres using a single script but in my case I have multiple scripts. 

Thanks,

**Comment by the-redback** [comment]
Hi @frouzbeh, The initialize part will run all the script that is available in `Init Volume of CRD`. But it will skip the scripts from child folders, though.

**Comment by frouzbeh** [comment]
@the-redback  thank you.
