### ISSUE TITLE
Resource requests and limits are not applied to monitoring exporter

### ISSUE THREAD

**Issue by guilleironhack** [kubedb/project#403]
Sorry for the vague issue description but my context is exactly the same as #311, but using MongoDB and adding the monitoring feature with coreos prometheus operator. 

In the created statefulset both mongo and init containers have the resource limits, but the exporter does not and hence the conflict with a `ResourceQuota` in a namespace.

**Comment by hossainemruz** [comment]
@guilleironhack  what KubeDB version are you using? It has been fixed in this PR https://github.com/kubedb/mongodb/pull/122 and is available in `0.9.0`.

**Comment by guilleironhack** [comment]
I'm using `0.9.0` and you're right, it should work. I was assuming that it would respect the resource limits from `spec.podTemplate.spec.resources`, but from the code from kubedb/mongodb#122 the  I see that the resource limits for the exporter should be in `spec.monitor.resources`.

Is this right? In that case, I tried to find it in the documentation with no luck.

**Comment by hossainemruz** [comment]
You are right. We haven't documented it. I have opened [this](https://github.com/kubedb/project/issues/404) issue address it.

**Comment by guilleironhack** [comment]
That's wonderful. Thanks!
