### ISSUE TITLE
Issues & Enhacements with the kubedb-cli deployment script on Windows using MINGW64

### ISSUE THREAD

**Issue by sherifkayad** [kubedb/project#415]
Hello fellaz,

Currently I have the following issues / enhancement requests for the kubedb-cli deployment script:

1. account for not only MINGW32 but also 64 for the onessl installation --> simply MINGW*

2. use the kubedb operator version 0.10.0

3. change some of the defaults as follows:
3.1 KUBEDB_IMAGE_PULL_POLICY --> set to Always
3.2 KUBEDB_ENABLE_ANALYTICS --> set to false
3.3 MONITORING_ENABLE --> set to true
3.4 MONITORING_AGENT --> set to $MONITORING_AGENT_COREOS_OPERATOR
3.5 PROMETHEUS_NAMESPACE --> set to "monitoring"

4. use the script location of 'master' --> SCRIPT_LOCATION set to "curl -fsSL https://raw.githubusercontent.com/kubedb/cli/master/"

5. No need to deploy the api server cert to prometheus when using the CoreOS Operator --> simply use insecureSkipVerify: true in the service monitor

If the above is fine with you, then I have a commit ready to be pushed and a pull request to be opened ;)

**Comment by sherifkayad** [comment]
Pull Request Pull Request https://github.com/kubedb/cli/pull/390

**Comment by tamalsaha** [comment]
Done.
