### ISSUE TITLE
Topology ES with zone awareness in cloud environments

### ISSUE THREAD

**Issue by mcortinas** [kubedb/project#418]
We want deploy ES on cloud environments such us GKE or EKS.

I think in order to make more easy GKE/EKS upgrades without downtime we could add affinity rules [https://kubernetes.io/docs/concepts/configuration/assign-pod-node/] aligned to data location awareness in order to make possible:

- 1 ES cluster in multi zones with 1 replica per zone.
- 1 ES in just 1 zone with 1 replica in different node-pools [https://cloud.google.com/kubernetes-engine/docs/concepts/node-pools]

**Comment by erik-stephens** [comment]
Similar to #334

**Comment by tamalsaha** [comment]
#499

**Comment by tamalsaha** [comment]
This issue has been resolved in KubeDB release v2021.03.17 . Please open a new bug if you still see this issue.
