### ISSUE TITLE
Mongodb verssion not found

### ISSUE THREAD

**Issue by botzill** [kubedb/project#419]
Hi.

I installed kubedb v.0.9.0. 

When I do:

```
kubectl get mongodbversions -n kube-system
NAME     VERSION   DB_IMAGE              DEPRECATED   AGE
3.4      3.4       kubedb/mongo:3.4      true         3h
3.4-v1   3.4       kubedb/mongo:3.4-v1   true         3h
3.4-v2   3.4       kubedb/mongo:3.4-v2                3h
3.6      3.6       kubedb/mongo:3.6      true         3h
3.6-v1   3.6       kubedb/mongo:3.6-v1   true         3h
3.6-v2   3.6       kubedb/mongo:3.6-v2                3h
4.0      4.0.5     kubedb/mongo:4.0                   3h
4.0.5    4.0.5     kubedb/mongo:4.0.5                 3h
4.1.7    4.1.7     kubedb/mongo:4.1.7                 3h
```

But when using `kubedb/mongo:4.1.7` does not work because, well, clearly not here https://hub.docker.com/r/kubedb/mongo/tags. Any plans create those images or this is smth that anyone needs to create by themselves?

Thx.

**Comment by botzill** [comment]
I see it's here, but I guess was not pushed

https://github.com/kubedb/mongodb/blob/master/hack/docker/mongo/4.1.7/Dockerfile

**Comment by the-redback** [comment]
It is part of 0.10.0 release. How you ended up with these `mongodbversions`?

**Comment by botzill** [comment]
I did install version 0.9.0 using helm from official documentation: https://kubedb.com/docs/0.9.0/setup/install/.

**Comment by the-redback** [comment]
I see. These docker images are not pushed into dockerhub. Other than that, the dockerfiles are alright. We push new images only when we release another version.

I am working on documentation. Let's see how long it can take. But, I guess within a week. :)

**Comment by botzill** [comment]
Great. For now I did use those dockerfiles and build images myself, Waiting for official release 👍 .
