### ISSUE TITLE
Installing KubeDb operator fails ver 0.9.0

### ISSUE THREAD

**Issue by martinounap** [kubedb/project#426]
Hi, our installation fails. It seems that catalog creation is broken.

`curl -fsSL https://raw.githubusercontent.com/kubedb/cli/0.9.0-rc.0/hack/deploy/kubedb.sh | bash
checking kubeconfig context
k8s-test-1

Downloading onessl ...
checking whether extended apiserver feature is enabled

KUBEDB_BYPASS_VALIDATING_WEBHOOK_XRAY=false
KUBEDB_CATALOG=all
KUBEDB_DOCKER_REGISTRY=kubedb
KUBEDB_ENABLE_ANALYTICS=true
KUBEDB_ENABLE_APISERVER=true
KUBEDB_ENABLE_MUTATING_WEBHOOK=true
KUBEDB_ENABLE_RBAC=true
KUBEDB_ENABLE_STATUS_SUBRESOURCE=true
KUBEDB_ENABLE_VALIDATING_WEBHOOK=true
KUBEDB_IMAGE_PULL_POLICY=IfNotPresent
KUBEDB_IMAGE_PULL_SECRET=
KUBEDB_NAMESPACE=kube-system
KUBEDB_OPERATOR_NAME=operator
KUBEDB_OPERATOR_TAG=0.9.0-rc.0
KUBEDB_PURGE=0
KUBEDB_RUN_ON_MASTER=0
KUBEDB_SERVICE_ACCOUNT=kubedb-operator
KUBEDB_UNINSTALL=0
KUBEDB_USE_KUBEAPISERVER_FQDN_FOR_AKS=true
KUBEDB_WEBHOOK_SIDE_EFFECTS=

Wrote ca certificates in  /root/k8s-test-2
Wrote server certificates in  /root/k8s-test-2
deployment.apps/kubedb-operator created
secret/kubedb-server-cert created
service/kubedb-operator created
apiservice.apiregistration.k8s.io/v1alpha1.validators.kubedb.com created
apiservice.apiregistration.k8s.io/v1alpha1.mutators.kubedb.com created
serviceaccount/kubedb-operator created
clusterrole.rbac.authorization.k8s.io/kubedb-operator reconciled
clusterrolebinding.rbac.authorization.k8s.io/kubedb-operator reconciled
rolebinding.rbac.authorization.k8s.io/kubedb-server-extension-server-authentication-reader reconciled
clusterrolebinding.rbac.authorization.k8s.io/kubedb-server-auth-delegator reconciled
clusterrole.rbac.authorization.k8s.io/kubedb:core:admin reconciled
clusterrole.rbac.authorization.k8s.io/kubedb:core:edit reconciled
clusterrole.rbac.authorization.k8s.io/kubedb:core:view reconciled
clusterrole.rbac.authorization.k8s.io/appscode:appcatalog:admin reconciled
clusterrole.rbac.authorization.k8s.io/appscode:appcatalog:view reconciled
validatingwebhookconfiguration.admissionregistration.k8s.io/validators.kubedb.com created
mutatingwebhookconfiguration.admissionregistration.k8s.io/mutators.kubedb.com created

waiting until kubedb operator deployment is ready
waiting until kubedb apiservice is available
waiting until kubedb crds are ready

installing KubeDB Elasticsearch catalog
unable to recognize "STDIN": no matches for kind "ElasticsearchVersion" in version "catalog.kubedb.com/v1alpha1"
unable to recognize "STDIN": no matches for kind "ElasticsearchVersion" in version "catalog.kubedb.com/v1alpha1"
unable to recognize "STDIN": no matches for kind "ElasticsearchVersion" in version "catalog.kubedb.com/v1alpha1"
unable to recognize "STDIN": no matches for kind "ElasticsearchVersion" in version "catalog.kubedb.com/v1alpha1"
unable to recognize "STDIN": no matches for kind "ElasticsearchVersion" in version "catalog.kubedb.com/v1alpha1"
unable to recognize "STDIN": no matches for kind "ElasticsearchVersion" in version "catalog.kubedb.com/v1alpha1"
unable to recognize "STDIN": no matches for kind "ElasticsearchVersion" in version "catalog.kubedb.com/v1alpha1"
unable to recognize "STDIN": no matches for kind "ElasticsearchVersion" in version "catalog.kubedb.com/v1alpha1"
unable to recognize "STDIN": no matches for kind "ElasticsearchVersion" in version "catalog.kubedb.com/v1alpha1"
unable to recognize "STDIN": no matches for kind "ElasticsearchVersion" in version "catalog.kubedb.com/v1alpha1"
unable to recognize "STDIN": no matches for kind "ElasticsearchVersion" in version "catalog.kubedb.com/v1alpha1"
unable to recognize "STDIN": no matches for kind "ElasticsearchVersion" in version "catalog.kubedb.com/v1alpha1"
unable to recognize "STDIN": no matches for kind "ElasticsearchVersion" in version "catalog.kubedb.com/v1alpha1"
unable to recognize "STDIN": no matches for kind "ElasticsearchVersion" in version "catalog.kubedb.com/v1alpha1"
`

and after words, when I try to vreate CRD manually I get same like error:

`kubectl apply -f pvt-postgresversion.yaml
error: unable to recognize "pvt-postgresversion.yaml": no matches for kind "postgresversions" in version "catalog.kubedb.com/v1alpha1"`

**Comment by hossainemruz** [comment]
@martinounap why are you trying to install an `0.9.0-rc` instead of `0.9.0` final release?  Install final release following instruction from here. https://kubedb.com/docs/0.9.0/setup/install/

**Comment by martinounap** [comment]
Yes, you are right, but it did not change anything :(

still:

`curl -fsSL https://raw.githubusercontent.com/kubedb/cli/0.9.0/hack/deploy/kubedb.sh | bash
checking kubeconfig context
k8s-test-1

Downloading onessl ...
checking whether extended apiserver feature is enabled

KUBEDB_BYPASS_VALIDATING_WEBHOOK_XRAY=false
KUBEDB_CATALOG=all
KUBEDB_DOCKER_REGISTRY=kubedb
KUBEDB_ENABLE_ANALYTICS=true
KUBEDB_ENABLE_APISERVER=true
KUBEDB_ENABLE_MUTATING_WEBHOOK=true
KUBEDB_ENABLE_RBAC=true
KUBEDB_ENABLE_STATUS_SUBRESOURCE=true
KUBEDB_ENABLE_VALIDATING_WEBHOOK=true
KUBEDB_IMAGE_PULL_POLICY=IfNotPresent
KUBEDB_IMAGE_PULL_SECRET=
KUBEDB_NAMESPACE=kube-system
KUBEDB_OPERATOR_NAME=operator
KUBEDB_OPERATOR_TAG=0.9.0
KUBEDB_PURGE=0
KUBEDB_RUN_ON_MASTER=0
KUBEDB_SERVICE_ACCOUNT=kubedb-operator
KUBEDB_UNINSTALL=0
KUBEDB_USE_KUBEAPISERVER_FQDN_FOR_AKS=true
KUBEDB_WEBHOOK_SIDE_EFFECTS=

Wrote ca certificates in  /root/k8s-test-2
Wrote server certificates in  /root/k8s-test-2
deployment.apps/kubedb-operator created
secret/kubedb-server-cert created
service/kubedb-operator created
apiservice.apiregistration.k8s.io/v1alpha1.validators.kubedb.com created
apiservice.apiregistration.k8s.io/v1alpha1.mutators.kubedb.com created
serviceaccount/kubedb-operator created
clusterrole.rbac.authorization.k8s.io/kubedb-operator reconciled
clusterrolebinding.rbac.authorization.k8s.io/kubedb-operator reconciled
rolebinding.rbac.authorization.k8s.io/kubedb-server-extension-server-authentication-reader reconciled
clusterrolebinding.rbac.authorization.k8s.io/kubedb-server-auth-delegator reconciled
clusterrole.rbac.authorization.k8s.io/kubedb:core:admin reconciled
clusterrole.rbac.authorization.k8s.io/kubedb:core:edit reconciled
clusterrole.rbac.authorization.k8s.io/kubedb:core:view reconciled
clusterrole.rbac.authorization.k8s.io/appscode:appcatalog:admin reconciled
clusterrole.rbac.authorization.k8s.io/appscode:appcatalog:view reconciled
validatingwebhookconfiguration.admissionregistration.k8s.io/validators.kubedb.com created
mutatingwebhookconfiguration.admissionregistration.k8s.io/mutators.kubedb.com created

waiting until kubedb operator deployment is ready
waiting until kubedb apiservice is available
waiting until kubedb crds are ready

installing KubeDB Elasticsearch catalog
unable to recognize "STDIN": no matches for kind "ElasticsearchVersion" in version "catalog.kubedb.com/v1alpha1"
unable to recognize "STDIN": no matches for kind "ElasticsearchVersion" in version "catalog.kubedb.com/v1alpha1"
unable to recognize "STDIN": no matches for kind "ElasticsearchVersion" in version "catalog.kubedb.com/v1alpha1"
unable to recognize "STDIN": no matches for kind "ElasticsearchVersion" in version "catalog.kubedb.com/v1alpha1"
unable to recognize "STDIN": no matches for kind "ElasticsearchVersion" in version "catalog.kubedb.com/v1alpha1"
unable to recognize "STDIN": no matches for kind "ElasticsearchVersion" in version "catalog.kubedb.com/v1alpha1"
unable to recognize "STDIN": no matches for kind "ElasticsearchVersion" in version "catalog.kubedb.com/v1alpha1"
unable to recognize "STDIN": no matches for kind "ElasticsearchVersion" in version "catalog.kubedb.com/v1alpha1"
unable to recognize "STDIN": no matches for kind "ElasticsearchVersion" in version "catalog.kubedb.com/v1alpha1"
unable to recognize "STDIN": no matches for kind "ElasticsearchVersion" in version "catalog.kubedb.com/v1alpha1"
unable to recognize "STDIN": no matches for kind "ElasticsearchVersion" in version "catalog.kubedb.com/v1alpha1"
unable to recognize "STDIN": no matches for kind "ElasticsearchVersion" in version "catalog.kubedb.com/v1alpha1"
unable to recognize "STDIN": no matches for kind "ElasticsearchVersion" in version "catalog.kubedb.com/v1alpha1"
unable to recognize "STDIN": no matches for kind "ElasticsearchVersion" in version "catalog.kubedb.com/v1alpha1"
`

**Comment by martinounap** [comment]
Our k8s versions:

kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:08:12Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.6", GitCommit:"b1d75deca493a24a2f87eb1efde1a569e52fc8d9", GitTreeState:"clean", BuildDate:"2018-12-16T04:30:10Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

**Comment by martinounap** [comment]
I tyed to update k8s claster, but still same problem :(

#kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:08:12Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.4", GitCommit:"f49fa022dbe63faafd0da106ef7e05a29721d3f1", GitTreeState:"clean", BuildDate:"2018-12-14T06:59:37Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}

**Comment by martinounap** [comment]
Sorry, with 11.6 we had problem, but when I updated to version 1.12.4 it started to work.

**Comment by HunterLarco** [comment]
This issue is occurring again in v0.13.0

```
unable to recognize "STDIN": no matches for kind "ElasticsearchVersion" in version "catalog.kubedb.com/v1alpha1
```
