### ISSUE TITLE
Proper way to install latest Postgres?

### ISSUE THREAD

**Issue by theshire-io** [kubedb/project#428]
Hello,

Sorry for the simple question but I couldn't find the answer in the docs.

I noticed that the master catalog now supports Postgres 11. What is the proper way to install kubedb to install PG 11? Do I need to also use the master branch of the cli?

Thank you.

**Comment by botzill** [comment]
Yes, I was looking for this as well. I was trying to build images myself from https://github.com/kubedb/postgres/tree/master/hack/docker. You can build you on images upload them to some docker registry and create a custom `PostgresVersion` pointing to your own images. But smth went wrong while I was trying to make a docker image for Postgres `11.1` and I wait for official release. Would great if there could be a way to test latest master as well.

**Comment by theshire-io** [comment]
With `0.10` now out, closing this.
