### ISSUE TITLE
Helm upgrade for kubedb operator chart regenerates caBundle and apiserver crts leading to TLS errors

### ISSUE THREAD

**Issue by sharkymcdongles** [kubedb/project#429]
On the latest version of the kubedb operator chart: 

appscode/kubedb         0.9.0           0.9.0

When you issue an upgrade command it will overwrite the caBundle definitions for v1alpha1.mutators.kubedb.com and v1alpha1.validators.kubedb.com as well as the tls.crt and tls.key definitions for the apiserver-cert.

Would be nice to not regenerate the certificate during an upgrade or to introduce a flag to not regenerate the certs if set to true and they exist.

**Comment by tamalsaha** [comment]
This should be already fixed in the latest release. We added a TLS cert checker that restarts the operator pod to reload the certificate.https://github.com/kmodules/apiserver/commit/065ee2704c89b9733a254b07921f497159eb313c

It should auto fix within 30 secs. Please reopen if not fixed.
