### ISSUE TITLE
Kubedb CRD wont be installed

### ISSUE THREAD

**Issue by martinounap** [kubedb/project#431]
We have RKE provisioned k8s cluster.

Our k8s is on version 1.12.4

Maybe you could help us? Or have any idea?
It just newly provisioned cluster, there was nothing deployed before.

_kubectl version_
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:08:12Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.4", GitCommit:"f49fa022dbe63faafd0da106ef7e05a29721d3f1", GitTreeState:"clean", BuildDate:"2018-12-14T06:59:37Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}

What we get on deploy:

_curl -fsSL https://raw.githubusercontent.com/kubedb/cli/0.9.0/hack/deploy/kubedb.sh | bash_
checking kubeconfig context
k8s-test-2

Downloading onessl ...
checking whether extended apiserver feature is enabled

KUBEDB_BYPASS_VALIDATING_WEBHOOK_XRAY=false
KUBEDB_CATALOG=all
KUBEDB_DOCKER_REGISTRY=kubedb
KUBEDB_ENABLE_ANALYTICS=true
KUBEDB_ENABLE_APISERVER=true
KUBEDB_ENABLE_MUTATING_WEBHOOK=true
KUBEDB_ENABLE_RBAC=true
KUBEDB_ENABLE_STATUS_SUBRESOURCE=true
KUBEDB_ENABLE_VALIDATING_WEBHOOK=true
KUBEDB_IMAGE_PULL_POLICY=IfNotPresent
KUBEDB_IMAGE_PULL_SECRET=
KUBEDB_NAMESPACE=kube-system
KUBEDB_OPERATOR_NAME=operator
KUBEDB_OPERATOR_TAG=0.9.0
KUBEDB_PURGE=0
KUBEDB_RUN_ON_MASTER=0
KUBEDB_SERVICE_ACCOUNT=kubedb-operator
KUBEDB_UNINSTALL=0
KUBEDB_USE_KUBEAPISERVER_FQDN_FOR_AKS=true
KUBEDB_WEBHOOK_SIDE_EFFECTS=sideEffects: None

Wrote ca certificates in  /root/k8s-test-2
Wrote server certificates in  /root/k8s-test-2
deployment.apps/kubedb-operator created
secret/kubedb-server-cert created
service/kubedb-operator created
apiservice.apiregistration.k8s.io/v1alpha1.validators.kubedb.com created
apiservice.apiregistration.k8s.io/v1alpha1.mutators.kubedb.com created
serviceaccount/kubedb-operator created
clusterrole.rbac.authorization.k8s.io/kubedb-operator reconciled
clusterrolebinding.rbac.authorization.k8s.io/kubedb-operator reconciled
rolebinding.rbac.authorization.k8s.io/kubedb-server-extension-server-authentication-reader reconciled
clusterrolebinding.rbac.authorization.k8s.io/kubedb-server-auth-delegator reconciled
clusterrole.rbac.authorization.k8s.io/kubedb:core:admin reconciled
clusterrole.rbac.authorization.k8s.io/kubedb:core:edit reconciled
clusterrole.rbac.authorization.k8s.io/kubedb:core:view reconciled
clusterrole.rbac.authorization.k8s.io/appscode:appcatalog:admin reconciled
clusterrole.rbac.authorization.k8s.io/appscode:appcatalog:view reconciled
validatingwebhookconfiguration.admissionregistration.k8s.io/validators.kubedb.com created
mutatingwebhookconfiguration.admissionregistration.k8s.io/mutators.kubedb.com created

waiting until kubedb operator deployment is ready
waiting until kubedb apiservice is available
waiting until kubedb crds are ready

installing KubeDB Elasticsearch catalog
unable to recognize "STDIN": no matches for kind "ElasticsearchVersion" in version "catalog.kubedb.com/v1alpha1"
unable to recognize "STDIN": no matches for kind "ElasticsearchVersion" in version "catalog.kubedb.com/v1alpha1"
unable to recognize "STDIN": no matches for kind "ElasticsearchVersion" in version "catalog.kubedb.com/v1alpha1"
unable to recognize "STDIN": no matches for kind "ElasticsearchVersion" in version "catalog.kubedb.com/v1alpha1"
unable to recognize "STDIN": no matches for kind "ElasticsearchVersion" in version "catalog.kubedb.com/v1alpha1"
unable to recognize "STDIN": no matches for kind "ElasticsearchVersion" in version "catalog.kubedb.com/v1alpha1"
unable to recognize "STDIN": no matches for kind "ElasticsearchVersion" in version "catalog.kubedb.com/v1alpha1"
unable to recognize "STDIN": no matches for kind "ElasticsearchVersion" in version "catalog.kubedb.com/v1alpha1"
unable to recognize "STDIN": no matches for kind "ElasticsearchVersion" in version "catalog.kubedb.com/v1alpha1"
unable to recognize "STDIN": no matches for kind "ElasticsearchVersion" in version "catalog.kubedb.com/v1alpha1"
unable to recognize "STDIN": no matches for kind "ElasticsearchVersion" in version "catalog.kubedb.com/v1alpha1"
unable to recognize "STDIN": no matches for kind "ElasticsearchVersion" in version "catalog.kubedb.com/v1alpha1"
unable to recognize "STDIN": no matches for kind "ElasticsearchVersion" in version "catalog.kubedb.com/v1alpha1"
unable to recognize "STDIN": no matches for kind "ElasticsearchVersion" in version "catalog.kubedb.com/v1alpha1"

**Comment by the-redback** [comment]
Can you provide the log of `kubedb-operator` deployment pod?

**Comment by martinounap** [comment]
Hi

We have upgraded all components and started to use Centos 7 as OS. After that we have had no problems.

Thank you for that kind of a nice solution :D
