### ISSUE TITLE
Allow custom registry for InitContainer

### ISSUE THREAD

**Issue by chiefy** [kubedb/project#465]
We're using the operator inside a locked-down VPC, so we can't access docker hub, so it'd be great to [allow for custom docker registry here](https://github.com/kubedb/elasticsearch/blob/2389656c055e5444b9f1d6605ba13e1e16c79279/test/e2e/framework/elastichsearch_version.go#L32)!

**Comment by tamalsaha** [comment]
This has been fixed in upcoming release 0.11.0 .

Dup https://github.com/kubedb/project/issues/450

**Comment by chiefy** [comment]
thanks @tamalsaha  didn't see that other issue.
