### ISSUE TITLE
[mysql] backupSchedule not creating CronJob 

### ISSUE THREAD

**Issue by botzill** [kubedb/project#480]
Hi.

I'm testing latest kubedb, `0.11.0` mysql and I see that no cron jobs is created for automatic backup. Does it work for mysql?

**Comment by tamalsaha** [comment]
It should. Can you share the MySQL yaml and logs from the operator? Do you have a failed snapshot that is causing issues?

**Comment by botzill** [comment]
Hi @tamalsaha .

Actually, it works now. I thought there should be created a CronJob and see it via the dashboard. Now I see snapshots created OK. 

Thx!
