### ISSUE TITLE
PostgreSQL 11.2

### ISSUE THREAD

**Issue by david-ecc** [kubedb/project#483]
[PostgreSQL 11.2 was released on 2019-02-14](https://www.postgresql.org/about/news/1920/), kubedb is still using version 11.1. 

The next version will be released on 2019-05-09 (see [roadmap](https://www.postgresql.org/developer/roadmap/)).

**Comment by david-ecc** [comment]
The tag `11.2` is missing on docker-hub, see: https://hub.docker.com/r/kubedb/postgres/tags

**Comment by the-redback** [comment]
Good catch... Give me some time to update it.

**Comment by the-redback** [comment]
I have pushed both `kubedb/postgres:11.2` & `kubedb/postgres-tools:11.2`. Please try and report anything weird you face. :)
