### ISSUE TITLE
Enable zone awareness for Elasticsearch

### ISSUE THREAD

**Issue by runningman84** [kubedb/project#499]
In a typical AWS setup you have multiple zones. In order to survive an zone outage the elasticsearch config should ensure that the corresponding az is exposed as a zone:

https://www.elastic.co/guide/en/elasticsearch/reference/master/allocation-awareness.html

Maybe it would be also useful to split the stateful sets to one set per zone?

**Comment by runningman84** [comment]
fixed title2

**Comment by runningman84** [comment]
fixed title

**Comment by tamalsaha** [comment]
https://github.com/kubernetes/enhancements/issues/895

**Comment by runningman84** [comment]
I do not think that the kubernetes failure domains alone are enough to tackle this issue. Elasticsearch itself needs to know which nodes runs in which az. Otherwise it cannot replicate the data across different az.

**Comment by tamalsaha** [comment]
This issue has been resolved in KubeDB release v2021.03.17 . Please open a new bug if you still see this issue.
