### ISSUE TITLE
Is it possible to do a rolling upgrade of Elasticsearch?

### ISSUE THREAD

**Issue by dsalazar32** [kubedb/project#506]
Is it possible, via the es CRD, to modify and initiate a graceful RollingUpdate of the version of Elasticsearch that's actively provisioned?  I'm able to accomplish this by patching the stateful sets generated but this isn't an ideal scenario.  If the stateful set is patched any subsequent run of the CRD will revert the images to the previously deployed version.

If I try to edit the `.spec.version` on the CRD it throws the following validation error:

```bash
Warning  Failed  13m    KubeDB operator  Fail to be ready Elasticsearch: "test-cluster".
Reason: StatefulSet.apps "client-test-cluster" is invalid: spec: 
Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden.
```

I was unable to find any documentation regarding upgrade paths for already in use kubedb managed elasticsearch clusters.  Please advise.

**Comment by tamalsaha** [comment]
This is not currently supported. We are planning to enable in future release. Dup #191 .
