### ISSUE TITLE
Increase /dev/shm limit for Postgres

### ISSUE THREAD

**Issue by tamalsaha** [kubedb/project#514]
https://github.com/kubedb/postgres/pull/269

**Comment by tamalsaha** [comment]
Notes for posterity:

- https://github.com/docker-library/postgres/issues/416
- https://stackoverflow.com/a/43374204/244009
- https://github.com/kubernetes/kubernetes/issues/28272

ToDo:
- [ ] Add a test that increases the `shared_buffer` limit beyond Docker's default . https://wiki.postgresql.org/wiki/Tuning_Your_PostgreSQL_Server

**Comment by iagooa** [comment]
Hi @tamalsaha,

this feature has been integrated into the v0.13.0-rc.0?

Thanks!

**Comment by tamalsaha** [comment]
This feature has been released.
