### ISSUE TITLE
Unable to create Postgres DB

### ISSUE THREAD

**Issue by AllaeddineEL** [kubedb/project#525]
after deploying kubedb operator with helm on kubernetes cluster v1.13.3, I'm not able to create postgres database with the following message:
`Error from server (InternalError): error when creating "db.yaml": Internal error occurred: failed calling webhook "postgres.mutators.kubedb.com": Post https://kubernetes.default.svc:443/apis/mutators.kubedb.com/v1alpha1/postgresmutators: Service Unavailable`
After checking the apiservice, found out both  `v1alpha1.mutators.kubedb.com` and `v1alpha1.validators.kubedb.com` failed the discovery check with this message `no response from https://10.233.57.221:443: Get https://10.233.57.221:443: Service Unavailable`

**Comment by the-redback** [comment]
@AllaeddineEL 
How you provision your cluster?
also, what kubedb version you are trying to install?

**Comment by AllaeddineEL** [comment]
the cluster is provisioned using kubespray on an openstack environment 
The helm chart version is 0.12.0 as well as the app version

**Comment by the-redback** [comment]
Can you get `$ kubectl get svc -n kube-system kubedb-operator -o yaml` ?

**Comment by AllaeddineEL** [comment]
`apiVersion: v1                                                 
kind: Service                                                  
metadata:                                                      
  creationTimestamp: "2019-05-15T08:32:53Z"                    
  labels:                                                      
    app: kubedb                                                
    chart: kubedb-0.12.0                                       
    heritage: Tiller                                           
    release: baseline-kubedb                                   
  name: baseline-kubedb                                        
  namespace: kubedb                                            
  resourceVersion: "20491184"                                  
  selfLink: /api/v1/namespaces/kubedb/services/baseline-kubedb 
  uid: 086f0360-76ec-11e9-a75a-fa163e0898a5                    
spec:                                                          
  clusterIP: 10.233.57.221                                     
  ports:                                                       
  - name: api                                                  
    port: 443                                                  
    protocol: TCP                                              
    targetPort: 8443                                           
  selector:                                                    
    app: kubedb                                                
    release: baseline-kubedb                                   
  sessionAffinity: None                                        
  type: ClusterIP                                              
status:                                                        
  loadBalancer: {} `

**Comment by AllaeddineEL** [comment]
running curl request from another pod
```
# curl -k https://10.233.57.221:443/apis
{
  "kind": "APIGroupList",
  "groups": [
    {
      "name": "mutators.kubedb.com",
      "versions": [
        {
          "groupVersion": "mutators.kubedb.com/v1alpha1",
          "version": "v1alpha1"
        }
      ],
      "preferredVersion": {
        "groupVersion": "mutators.kubedb.com/v1alpha1",
        "version": "v1alpha1"
      },
      "serverAddressByClientCIDRs": [
        {
          "clientCIDR": "0.0.0.0/0",
          "serverAddress": ":8443"
        }
      ]
    },
    {
      "name": "validators.kubedb.com",
      "versions": [
        {
          "groupVersion": "validators.kubedb.com/v1alpha1",
          "version": "v1alpha1"
        }
      ],
      "preferredVersion": {
        "groupVersion": "validators.kubedb.com/v1alpha1",
        "version": "v1alpha1"
      },
      "serverAddressByClientCIDRs": [
        {
          "clientCIDR": "0.0.0.0/0",
          "serverAddress": ":8443"
        }
      ]
    }
  ]
}
```

**Comment by the-redback** [comment]
`kubectl describe apiservice -l app=kubedb`? you can remove spec.caBundle.

**Comment by AllaeddineEL** [comment]
```
Name:         v1alpha1.mutators.kubedb.com
Namespace:
Labels:       app=kubedb
              chart=kubedb-0.12.0
              heritage=Tiller
              release=baseline-kubedb
Annotations:  <none>
API Version:  apiregistration.k8s.io/v1
Kind:         APIService
Metadata:
  Creation Timestamp:  2019-05-15T10:22:57Z
  Resource Version:    20507462
  Self Link:           /apis/apiregistration.k8s.io/v1/apiservices/v1alpha1.mutators.kubedb.com
  UID:                 685e3715-76fb-11e9-a75a-fa163e0898a5
Spec:
  Ca Bundle:               XXXX
  Group:                   mutators.kubedb.com
  Group Priority Minimum:  10000
  Service:
    Name:            baseline-kubedb
    Namespace:       kubedb
  Version:           v1alpha1
  Version Priority:  15
Status:
  Conditions:
    Last Transition Time:  2019-05-15T10:22:57Z
    Message:               no response from https://10.233.57.221:443: Get https://10.233.57.221:443: Service Unavailable
    Reason:                FailedDiscoveryCheck
    Status:                False
    Type:                  Available
Events:                    <none>

---
Name:         v1alpha1.validators.kubedb.com
Namespace:
Labels:       app=kubedb
              chart=kubedb-0.12.0
              heritage=Tiller
              release=baseline-kubedb
Annotations:  <none>
API Version:  apiregistration.k8s.io/v1
Kind:         APIService
Metadata:
  Creation Timestamp:  2019-05-15T10:22:57Z
  Resource Version:    20507463
  Self Link:           /apis/apiregistration.k8s.io/v1/apiservices/v1alpha1.validators.kubedb.com
  UID:                 685d244a-76fb-11e9-a75a-fa163e0898a5
Spec:
  Ca Bundle:               XXXX
  Group:                   validators.kubedb.com
  Group Priority Minimum:  10000
  Service:
    Name:            baseline-kubedb
    Namespace:       kubedb
  Version:           v1alpha1
  Version Priority:  15
Status:
  Conditions:
    Last Transition Time:  2019-05-15T10:22:57Z
    Message:               no response from https://10.233.57.221:443: Get https://10.233.57.221:443: Service Unavailable
    Reason:                FailedDiscoveryCheck
    Status:                False
    Type:                  Available
Events:                    <none>
```

**Comment by AllaeddineEL** [comment]
@the-redback Thank you for your support, I've managed to resolve the problem.
The problem was in the kube-api-server pod, that has http proxy environment variables, after removing all these env vars, the problem is solved

**Comment by pmpetit** [comment]
Hello,
i have the same problem : 
Name:         v1alpha1.mutators.kubedb.com
Namespace:    
Labels:       app=kubedb
              chart=kubedb-0.12.0
              heritage=Tiller
              release=kubedb-operator
Annotations:  <none>
API Version:  apiregistration.k8s.io/v1
Kind:         APIService
Metadata:
  Creation Timestamp:  2019-06-19T09:29:44Z
  Resource Version:    30480173
  Self Link:           /apis/apiregistration.k8s.io/v1/apiservices/v1alpha1.mutators.kubedb.com
  UID:                 c5e48094-9274-11e9-9e0f-42010a2a1056
Spec:
  Ca Bundle:               LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM1ekNDQWMrZ0F3SUJBZ0lSQUwwZ05SVnBMUXphZ1pPYkJIdUlNVVF3RFFZSktvWklodmNOQVFFTEJRQXcKRFRFTE1Ba0dBMVVFQXhNQ1kyRXdIaGNOTVRrd05qRTVNRGt5T1RReldoY05Namt3TmpFMk1Ea3lPVFF6V2pBTgpNUXN3Q1FZRFZRUURFd0pqWVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTGNiCkFndVpJNTJEU1JvUVZRQzh6cmQyc2Z0Z29KOXhFa08wQ25UcWtQSHk3SlliQWJkR002V01TbkdxOFExSGtPV1MKck9UTGlDd2I3cjJjQVF1U0JKWlFkRzRHWkpGYTJSTEY4ZUFrdWtqYW9TbEluNEQzNU9pMzVyYWY0dFY5NVdiYQpUL0JWbHh3UzZBaitJL3g0bnc0NUtFVnhiRHB4cklad3JoWSt2UWRmSG9Xcmx5bWJZNVFRKy93aGdpenFOYy9WClVHZW5zZ1pkeVlRR3puaDZub2JGeS9KVW9EcnRaejlveDFkMFlFbjlQY3U1WEZNWGsrWk1POHEzOGRnRDhUbm0KZkNLb2pJcENUamQ5cUNDYThuMEhmY3NPdnN0NjU1MXR3YTNCVVpFVVpxbXA1L2l2eWJJMTIza3p4RUZad09UZwpOWVV0YVgrYXBldEZTc2trMVE4Q0F3RUFBYU5DTUVBd0RnWURWUjBQQVFIL0JBUURBZ0trTUIwR0ExVWRKUVFXCk1CUUdDQ3NHQVFVRkJ3TUJCZ2dyQmdFRkJRY0RBakFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTBHQ1NxR1NJYjMKRFFFQkN3VUFBNElCQVFDWm51V2FETlpLQ2VXZ2VSVk5uMXlYcWhCRlBDVURkZHZkdUVsb283aWZ0d1lKQUxiMgo4WUREVFdYMEFIcm5ZcStTQkp0ajNDY1R4YVhjTnl3NGZ6ZXYwL1NKMU04aUNVK2p4bWtlTG9XeEg2VXBCMEN4CjZqbWcxUEJPT1czQXhZN3FCWlJKcjdXT3dob0l6dS94cWFMeFZFREVIUUdydmFmTllNUDRZcGp2NUNpWi9MSGsKNjdCWndmb2xuY3lYUTNTdGlnY2drbWJQRkJzNDRNWDh0cEhvSXZEYnhuVXErRTR3ZEdSNHZENUYvMW9Ma0srVgovTlNpdll1OUFUWFprUm9mTlR4QUxFT25iaUJNOEFEVzhudVRtVmp4SldPUm9jZStHNHFJTC82VVUzLytSb0l1CnVKTzQ5S25UNm41UUVidUJzOGtLVm4zSTJycncvZW56WTdTTQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  Group:                   mutators.kubedb.com
  Group Priority Minimum:  10000
  Service:
    Name:            kubedb-operator
    Namespace:       kubedb-system
  Version:           v1alpha1
  Version Priority:  15
Status:
  Conditions:
    Last Transition Time:  2019-06-19T09:29:44Z
    Message:               no response from https://10.43.114.158:8443: Get https://10.43.114.158:8443: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
    Reason:                FailedDiscoveryCheck
    Status:                False
    Type:                  Available
Events:                    <none>


Name:         v1alpha1.validators.kubedb.com
Namespace:    
Labels:       app=kubedb
              chart=kubedb-0.12.0
              heritage=Tiller
              release=kubedb-operator
Annotations:  <none>
API Version:  apiregistration.k8s.io/v1
Kind:         APIService
Metadata:
  Creation Timestamp:  2019-06-19T09:29:44Z
  Resource Version:    30480174
  Self Link:           /apis/apiregistration.k8s.io/v1/apiservices/v1alpha1.validators.kubedb.com
  UID:                 c5e977c5-9274-11e9-9e0f-42010a2a1056
Spec:
  Group:                   validators.kubedb.com
  Group Priority Minimum:  10000
  Service:
    Name:            kubedb-operator
    Namespace:       kubedb-system
  Version:           v1alpha1
  Version Priority:  15
Status:
  Conditions:
    Last Transition Time:  2019-06-19T09:29:44Z
    Message:               no response from https://10.43.114.158:8443: Get https://10.43.114.158:8443: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
    Reason:                FailedDiscoveryCheck
    Status:                False
    Type:                  Available
Events:                    <none>
