### ISSUE TITLE
Upgrade Elasticsearch

### ISSUE THREAD

**Issue by lcasassa** [kubedb/project#536]
Hi, What are the steps to update an elasticsearch from version 5.6.4-v1 to 6.5.3? I tried just changing the version on the elasticsearch type resource and got:

```Warning  Failed      12m   KubeDB operator  Fail to be ready Elasticsearch: "elasticsearch". Reason: StatefulSet.apps "client-elasticsearch" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden.```

I can't find anything on the docs for updating databases.

Thanks!

**Comment by lcasassa** [comment]
It looks like I just have to update the version and delete all the statefulsets (not the pvc). Am I in the right direction?

**Comment by ahmadalli** [comment]
I'm facing the same issue
@lcasassa I think that would be the dirty solution

**Comment by tamalsaha** [comment]
This issue has been resolved in KubeDB release v2021.03.17 . Please open a new bug if you still see this issue.
