### ISSUE TITLE
Admission webhooks can't be used when kube apiserver is accesible without verifying its TLS

### ISSUE THREAD

**Issue by cmoulliard** [kubedb/project#584]
## Issue

If I try to install kubedb on ocp 3.11 (Openshift Kubernetes distribution), I get this error message 

`Admission webhooks can't be used when kube apiserver is accesible without verifying its TLS certificate (insecure-skip-tls-verify : true).` 

Is there a workaround ?

Command used is
```kubectl create ns kubedb
curl -fsSL https://raw.githubusercontent.com/kubedb/cli/0.12.0/hack/deploy/kubedb.sh \
    | bash -s -- --namespace=kubedb --install-catalog=postgres
```

**Comment by cmoulliard** [comment]
No matter if we try to disable or enable the TLS verification, that will fail

```
kubectl config set-cluster 192-168-99-50:8443 --insecure-skip-tls-verify=false
Cluster "192-168-99-50:8443" set.

kubectl create ns kubedb
curl -fsSL https://raw.githubusercontent.com/kubedb/cli/0.12.0/hack/deploy/kubedb.sh \
    | bash -s -- --namespace=kubedb --install-catalog=postgres

Unable to connect to the server: x509: certificate signed by unknown authority
checking kubeconfig context
default/192-168-99-50:8443/admin

Downloading onessl ...
Unable to connect to the server: x509: certificate signed by unknown authority
in , execute error serverVersion is not found

AND


kubectl config set-cluster 192-168-99-50:8443 --insecure-skip-tls-verify=true
Cluster "192-168-99-50:8443" set.

kubectl create ns kubedb
curl -fsSL https://raw.githubusercontent.com/kubedb/cli/0.12.0/hack/deploy/kubedb.sh \
    | bash -s -- --namespace=kubedb --install-catalog=postgres
Error from server (AlreadyExists): namespaces "kubedb" already exists
checking kubeconfig context
default/192-168-99-50:8443/admin

Downloading onessl ...
checking whether extended apiserver feature is enabled

Admission webhooks can't be used when kube apiserver is accesible without verifying its TLS certificate (insecure-skip-tls-verify : true).
```

I suspect that the issue is related to the fact that you use your own certificate for the API server instead of the certificates issued for the openshift server locally

**Comment by weenxin** [comment]
I Have meet this problem .

Your K8s Api Server must set ```insecure-skip-tls-verify : true``` 

And then you can use webhook .

**Comment by cmoulliard** [comment]
> Your K8s Api Server must set `insecure-skip-tls-verify : true`

Is it a parameter that you can define within the master-config.yml file of the K8s Api server ?

**Comment by weenxin** [comment]
@cmoulliard 

Sorry , My bad

In my ~/.kube/config , we use "insecure-skip-tls-verify: true" to skip the insecure-tls-verify, using user password to  verify

Then Admission webhooks  can not be used.

like the error message:

```
Admission webhooks can't be used when kube apiserver is accesible without verifying its TLS certificate (insecure-skip-tls-verify : true).
```
