### ISSUE TITLE
[MongoDB] Return NotMaster when perform write test after automatic failover

### ISSUE THREAD

**Issue by frbimo** [kubedb/project#587]
**Describe the bug**
MongoDB deployment using with replicaset failed to write after perform automatic failover. 

**Version of  Kubernetes**:
AKS kubernetes 1.12

**What happened**:
Testing automatic failover to mongoDB  replicaset after delete the primary pod. Re-connecting using Robo3T was succeed but writing returns error NotMaster. 

**What you expected to happen**:
How to connect  and writing to mongoDB even when primary is down. or master is not primary

**How to reproduce it** (as minimally and precisely as possible):
1. kubedb create -f kubedb-deployment.yaml
2. Create new db
3. db.tes.insert({"test01":"Ok"})

**Note**:
rs.isMaster()
```
{
    "hosts" : [ 
        "mgo-replicaset-0.mgo-replicaset-gvr.mongo-test.svc.cluster.local:27017", 
        "mgo-replicaset-1.mgo-replicaset-gvr.mongo-test.svc.cluster.local:27017", 
        "mgo-replicaset-2.mgo-replicaset-gvr.mongo-test.svc.cluster.local:27017"
    ],
    "setName" : "rs0",
    "setVersion" : 3,
    "ismaster" : false,
    "secondary" : true,
    "primary" : "mgo-replicaset-0.mgo-replicaset-gvr.mongo-test.svc.cluster.local:27017",
    "me" : "mgo-replicaset-1.mgo-replicaset-gvr.mongo-test.svc.cluster.local:27017",
}
```

**Comment by weenxin** [comment]
Please check this #422 issue

Did you connect to your cluster not instance.

## Steps

1. Node0 is primary 
2. Node0 die
3. Node1 is elected as master
4. Node0 restarted
5. Node0 is secondary node


If you reconnect to Node0 , then it is not master.

**Comment by frbimo** [comment]
@weenxin 
deployment has only 1 service. Client connect using IP assigned in the service.

**Comment by the-redback** [comment]
Hi @frbimo , I have added one comment on that issue. Please see the [comment here](https://github.com/kubedb/project/issues/422#issuecomment-514886861). It might help you to find a solution.

**Comment by the-redback** [comment]
I am closing this issue. For further discussion, you can comment on  #422.
