### ISSUE TITLE
[postgres] Don't participate in leader election if in known bad state

### ISSUE THREAD

**Issue by bodewig** [kubedb/project#593]
I'm creating a separate issue for what I've described in https://github.com/kubedb/project/issues/555#issuecomment-510921539 in order to make it more visible.

Sometimes a pod is in a state in which it must not become a primary under any circumstances.

My example is when the initial backup performed in secondary's run.sh fails - https://github.com/kubedb/postgres/blob/30937fd1c6fb8cf9bf21cf340231709b05a8fc13/hack/docker/postgres/10.6/scripts/replica/run.sh#L40 - because the connection to the current primary is lost. At this point in time the pod has removed the data directory completely and restarts (`pg_basebackup` returns with a non-zero exit code, and so does run.sh). When the pod comes up again and then happens to get elected as new primary all data will be lost - and the new empty databases get replicated to the remaining pods destroying all of them.

IMHO if a pod knows it is in no shape to become a primary it should mark the pod - a file on the persistent volume? - and simply not try to get elected as primary before the problem has been resolved.

**Comment by y-batsianouski** [comment]
Hello! 

We have the same issue with Postgres!

**Comment by splitice** [comment]
We hit this bug today. Fortunately on the development / staging infrastructure.

With a bug as serious as this Postgres replication should be removed from KubeDB until there is a proven solution.

**Comment by tamalsaha** [comment]
This issue has been resolved in KubeDB release v2021.03.17 .
