### ISSUE TITLE
validating-webhook.yaml and mutating-webhook.yaml is missing in cli project

### ISSUE THREAD

**Issue by weenxin** [kubedb/project#596]
##  Background

Trying to run Kubedb Operator on localhost with a kubernetes cluster in minikube using [this script](https://github.com/kubedb/operator/blob/master/hack/deploy/setup.sh)

## Steps to repeat errors

1. Clone operator project
2. Run ```./hack/deploy/setup.sh --run --minikube```

## Error Message

*cat: $GOPATH/src/github.com/kubedb/cli/hack/deploy/validating-webhook.yaml: No such file or directory*

## Method To Fix It 

1. Using "installer" project rather than "cli" project

**Comment by tamalsaha** [comment]
Fixed in https://github.com/kubedb/operator/pull/227
