### ISSUE TITLE
clientset complains on kubedb.dev 

### ISSUE THREAD

**Issue by skad0Osh** [kubedb/project#603]
Hi Guys, i am trying to use the clientset of kubedb but i keep getting following error during codegen (i got the api,codegen for kubedb from https://github.com/kubedb/apimachinery)
hack/codegen.sh
 docker run --rm -ti -u 504:20 -v ~/go/src/kubedb.dev/apimachinery:/go/src/kubedb.dev/apimachinery -w /go/src/kubedb.dev/apimachinery appscode/gengo:release-1.14 /go/src/k8s.io/code-generator/generate-groups.sh deepcopy,client,informer,lister kubedb.dev/apimachinery/client kubedb.dev/apimachinery/apis 'kubedb:v1alpha1 catalog:v1alpha1 config:v1alpha1 authorization:v1alpha1' --go-header-file /go/src/kubedb.dev/apimachinery/hack/gengo/boilerplate.go.txt
Generating deepcopy funcs
F0723 22:36:31.870698      11 main.go:86] Error: Failed making a parser: unable to add directory "kubedb.dev/apimachinery/apis/kubedb/v1alpha1": unable to import "kubedb.dev/apimachinery/apis/kubedb/v1alpha1": cannot find package "kubedb.dev/apimachinery/apis/kubedb/v1alpha1" in any of:
    /usr/local/go/src/kubedb.dev/apimachinery/apis/kubedb/v1alpha1 (from $GOROOT)
    /go/src/kubedb.dev/apimachinery/apis/kubedb/v1alpha1 (from $GOPATH)

Are there any instructions on how to generate this? If i use the already generated clientset, i get the following error:
in my code i am using the client as following:
 
import   kubedbClientset "github.com/kubedb/apimachinery/client/clientset/versioned"

restC := rest.Config{.. }
    ks, err := kubedbClientset.NewForConfig(&restC)
    if err != nil {
        panic(err)
    }

go run main.go

./main.go:67:41: cannot use config (type *"k8s.io/client-go/rest".Config) as type *"kubedb.dev/apimachinery/vendor/k8s.io/client-go/rest".Config in argument to versioned.NewForConfig

**Comment by tamalsaha** [comment]
You code should be in the `~/go/src/kubedb.dev/apimachinery` folder. Do you have it that way?

**Comment by skad0Osh** [comment]
Thanks for responding. yes it works if i move then code under ~/go/src/kubedb.dev/apimachiner.
But i would like to import the clientset as a regular package and use it, similar to any other generated clientsets ex:
Clientset, err = kubernetes.NewForConfig(config)
is that not possible?

**Comment by tamalsaha** [comment]
Yes. We have moved the clientset from github.com/kubedb/apimachinery in last release 0.12.0 to kubedb.dev/apimachinery@master. If you are working on new code, use the master branch. Once we release the next version 0.13.0, you should be able to depend on that.

**Comment by tamalsaha** [comment]
You can look at any of the operators as an example : https://github.com/kubedb/redis

**Comment by skad0Osh** [comment]
Thank you this works when using the go.dep like whats on kubedb/postgres i am able to use it now.
