### ISSUE TITLE
MongoDB support --archive option for backup/restore

### ISSUE THREAD

**Issue by sfitts** [kubedb/project#605]
Currently the MongoDB backup and restore jobs do not support the use of the `--archive` option to put the backup into a single archive file.   It would be really nice to have this option since it makes the resulting backup much easier to manage/move/download.

BTW -- if you try to add this option via your own args you just get an error since the resulting `mongodump` command line is illegal.

**Comment by the-redback** [comment]
I can verify that I was able to reproduce the error where `--archive` is [provided as user configuration part](https://kubedb.com/docs/0.12.0/guides/mongodb/configuration/using-crd-configuration/#snapshot-configuration) and ended up getting error: 

```
Failed: bad option: --out not allowed when --archive is specified
```

**Comment by the-redback** [comment]
- As we are deprecating snapshot, we are not gonna fix it in snapshot-tool.
- `--archive` support is added and default setup in [stashed/mongodb](https://github.com/stashed/mongodb) backup system. xref: https://github.com/stashed/mongodb/blob/master/pkg/backup.go#L200
