### ISSUE TITLE
retention policy

### ISSUE THREAD

**Issue by codejamninja** [kubedb/project#610]
I know how to get a retentionPolicy working for stash, but how to I make it work for kubedb?

**Comment by hossainemruz** [comment]
@codejamninja currently, KubeDB does not have a retention policy. Btw, we are moving backup part to database. So, you would be able to backup KubeDB databases using Stash.

**Comment by codejamninja** [comment]
What do you mean "we are moving backup part to database?"

**Comment by hossainemruz** [comment]
Ops!!! It would be `We are moving backup part of database to Stash`.

**Comment by codejamninja** [comment]
@hossainemruz what is the timeline for database stash backups?

**Comment by tamalsaha** [comment]
We are looking to cut a rc by end of this week. Then our team is out for a week due to Eid al-Adha vacation. Then we should cut a full release in 1-3 weeks depending in what report we get from users.

**Comment by codejamninja** [comment]
Ok, sounds great. Eid Saeed

**Comment by codejamninja** [comment]
Thanks for the hard work on this!
