### ISSUE TITLE
MongoDB -- maintain support for pre-SSPL licensed releases (aka 3.6.9)

### ISSUE THREAD

**Issue by sfitts** [kubedb/project#614]
The most recent version of KubeDB (0.12.0) requires an update to MongoDB version "3.6-v3" which corresponds to Mongo 3.6.12.  Unfortunately that release is under the new Mongo SSPL license which some companies (mine included) cannot run.

Given this we are holding our Mongo release at 3.6.9 and would like to see KubeDB continue to provide that as an option even as other improvements are made.

**Comment by tamalsaha** [comment]
sgtm.

**Comment by the-redback** [comment]
@sfitts , Do you know what is the pre-SSPL version for 3.4.x?

**Comment by the-redback** [comment]
Seems like 3.6.9 also contains SSPL license, ref: https://github.com/mongodb/mongo/blob/r3.6.9/LICENSE-Community.txt 

Mongodb is saying `All versions of MongoDB’s Community Server released on or after October 16, 2018, including patch fixes for prior versions, will be licensed under the SSPL.` [[ref](https://www.mongodb.com/licensing/server-side-public-license/faq)] and 3.6.9 is released 
on Nov 14, 2018 . [[ref](https://github.com/mongodb/mongo/releases/tag/r3.6.9).

**Comment by the-redback** [comment]
In my finding: pre-SSL (before October 16, 2018) versions are:

- [3.4.17](https://github.com/mongodb/mongo/releases/tag/r3.4.17)
- [3.6.8](https://github.com/mongodb/mongo/releases/tag/r3.6.8)
- [4.0.3](https://github.com/mongodb/mongo/releases/tag/r4.0.3)
- [4.1.4](https://github.com/mongodb/mongo/releases/tag/r4.1.4)

**Comment by sfitts** [comment]
Yes, this looks right.  At one point I seem to remember the line being drawn a bit later, but clearly that's not the case.
