### ISSUE TITLE
Support Postgres 11.4

### ISSUE THREAD

**Issue by sherifkayad** [kubedb/project#615]
Currently the latest Postgres version supported is 11.2 

11.4 is the current minor and it would be great to support it in kubedb

**Comment by david-ecc** [comment]
11.5 and 10.10 were released: https://www.postgresql.org/about/news/1960/

**Comment by david-ecc** [comment]
PostgreSQL 12.1, 11.6, 10.11, 9.6.16, 9.5.20, and 9.4.25 Released! https://www.postgresql.org/about/news/1994/

**Comment by tamalsaha** [comment]
This issue has been resolved in KubeDB release v2021.03.17 .
