### ISSUE TITLE
Install kubedb master version

### ISSUE THREAD

**Issue by codejamninja** [kubedb/project#616]
How do I install the latest kubedb from the master branches? I want to start testing the stash integration with kubedb and the latest version currently doesn't support it, but I see it in the latest code.

**Comment by the-redback** [comment]
1.` export REGISTRY=<registry-name>`
2. `make push` - to build and push the image to docker registry
3. `make install` - to install the operator.

`branch name`/`commit hash`(in case of master branch) is used as docker tag in `push` and `install` command.

**Comment by codejamninja** [comment]
Cool, thanks
