### ISSUE TITLE
MongoDB: Supporting inMemory storage engine using Percona Server for MongoDB

### ISSUE THREAD

**Issue by apu1111** [kubedb/project#617]
Hi,
This is a feature request to support 
1. Percona edition of MongoDB images in KubdDB.
2. inMemory storage engine to run MongoDB as inMemory cache.

This would need changing the way MongoDB currently deployed by KubeDB, mainly the startup scripts.

**Comment by weenxin** [comment]
Maybe can create a MongoDB with ```spec.storageType= Ephemeral ```  That will use kubernetes [empty directory]( https://kubernetes.io/docs/concepts/storage/volumes/#emptydir)

*By default, emptyDir volumes are stored on whatever medium is backing the node - that might be disk or SSD or network storage, depending on your environment. However, you can set the emptyDir.medium field to "Memory" to tell Kubernetes to mount a tmpfs (RAM-backed filesystem) for you instead. While tmpfs is very fast, be aware that unlike disks, tmpfs is cleared on node reboot and any files you write will count against your Container’s memory limit.*

But right now,  we can not assign param to ```emptyDir.medium``` to a MongoDB instance.

**Comment by tamalsaha** [comment]
ToDos:

1. kubedb/apimachiner

Add StorageType InMmeory

2. kubedb/mongodb-init-scripts

Init container scripts and doskerfiles

3. kubedb/installer

MongoDBVesion crd for percona mongo + exporter

4. kubedb/mongodb

Changes for in-memory
Test e2e using Ginkgo

5. kubedb/docs

Concepts Doc
Guides Doc showing in-memory databse
