### ISSUE TITLE
Catalog postgres-stash is not supported

### ISSUE THREAD

**Issue by codejamninja** [kubedb/project#619]
I get the following error when trying to install the `postgres-stash` catalog.

```
Catalog postgres-stash is not supported
```

https://appscode.com/products/stash/v0.9.0-rc.0/guides/latest/auto-backup/database/#install-via-helm-chart

**Comment by hossainemruz** [comment]
We haven't published the chart yet. We have to cut a release for KubeDB.

**Comment by codejamninja** [comment]
I'm assuming I have to wait a week before the release is cut?

**Comment by hossainemruz** [comment]
@codejamninja we haven't published the charts yet. Some works still needs to be done before publishing. Btw, if you want to install from source here you go:
1. Chart: https://github.com/stashed/postgres/tree/master/chart/stash-postgres
2. How to try locally: https://github.com/stashed/catalog/blob/master/CONTRIBUTING.md

We are sorry for the confusion. We didn't want to block KubeDB release for this.
