### ISSUE TITLE
Containerized mongoDB with recent version

### ISSUE THREAD

**Issue by michaelmass** [kubedb/project#620]
MondoDB isn't container aware in the version offered by kubedb. So we need to set the WiredTiger cache size inside the configuration to prevent the database from behing `OOMKilled`.

From the version `4.0.9` of MongoDB, the database sets a value `hostInfo.system.memLimitMB` that makes it container aware.

Could it be possible to offer a more recent version for mongoDB to get this feature ?

Is there a temporary fix to replace the version `4.0.5` with `4.0.9` ?

**Comment by the-redback** [comment]
We are adding new versions for MongoDB in next release. 
Here is the pr link: https://github.com/kubedb/mongodb/pull/171
Hopefully, We are also planning an rc release within a week.

But, if you want to make the changes anyway, you can try creating a docker image for 4.0.9 by replacing `4.0.5` in docker files [here](https://github.com/kubedb/mongodb/tree/0.5.0/hack/docker/mongo/4.0.5) and push the image in you docker repository.
Then, you need to update Mongodbversions crd by following [this doc](https://kubedb.com/docs/0.12.0/guides/postgres/custom-versions/setup/).

**Comment by the-redback** [comment]
About this issue, is updating the mongodb versions will solve this automatically?

**Comment by michaelmass** [comment]
Yes. In theory, mongodb will manage its memory using the `container` specification instead of the `host`. The `OOMKilled` won't be a problem anymore.

**Comment by tamalsaha** [comment]
This issue has been resolved in KubeDB release v2021.03.17 . Please open a new bug if you still see this issue.
