### ISSUE TITLE
Support postgis with own images

### ISSUE THREAD

**Issue by ManuelB** [kubedb/project#621]
Hi,
we need for our application Postgres 10.7 with PostGIS 2.5.2
I created the necessary images and published them to hub.docker.com

https://hub.docker.com/r/manuelb86/postgres/tags
https://hub.docker.com/r/manuelb86/postgres-tools/tags

It would be awesome if these could be directly added to kubedb.

My work is based on https://github.com/abkfenris/kubedb-postgis.

Thanks a lot
Manuel

**Comment by tamalsaha** [comment]
This issue has been resolved in KubeDB release v2021.03.17 . Please open a new bug if you still see this issue.
