### ISSUE TITLE
[Postgres] Ability to specify different resources for master and slaves

### ISSUE THREAD

**Issue by Mokto** [kubedb/project#644]
Hi ! 

I don't know if this is possible without major changes to the operator (1 stateful set for master, 1 for slaves). But it would be nice to set different resources values for master and slave.

As slaves are using A LOT less resources than the master container :) 

Thanks for you tool by the way, it's awesome.

**Comment by tamalsaha** [comment]
We don't plan to support this. Because the standbys can become master. So, those must be of same configuration.
