### ISSUE TITLE
kubedb-catalog Helm Installer automatically wait until crds are registered

### ISSUE THREAD

**Issue by weenxin** [kubedb/project#665]
## Background

When we install `appscode/kubedb-catalog`,  We need manually wait until crds are registered

## Solutions

Use `helm` pre-install hooks wait until  crds are registered

**Comment by DandyDeveloper** [comment]
A better option would be here to just combine the operator and catalog with a pre-install hook.

**Comment by tamalsaha** [comment]
This issue has been resolved in KubeDB release v2021.03.17 . Please open a new bug if you still see this issue.
