### ISSUE TITLE
[Security Feature] Add cert-manager support for PgBouncer

### ISSUE THREAD

**Issue by iamrz1** [kubedb/project#689]
[Cert-Manager](https://github.com/jetstack/cert-manager) can be used to issue self-signed certificates across `namespaces` using `Issuers` or across `clusters` using `ClusterIssuers`. These certificates can then be used to provide secure (TLS) connections between clients and PgBouncer.
PgBouncer can be configured to accept client certificates by setting a few client tls configuration parameters.

Using an `IssuerRef` field in PgBouncer crd, users can select the Issuer that should be used to generate certificates for PgbPuncer.

Connection requests to the PgBouncer can then be made using TLS certificates only, generated by the same Issuer or other Issuers with the same CA.

Similarly, connections from PgBouncer to PostgreSQL can also be made secure by setting a few server tls configuration parameters.

**Comment by tamalsaha** [comment]
This issue has been resolved in KubeDB release v2021.03.17 . Please open a new bug if you still see this issue.
