### ISSUE TITLE
KubeDB failed to deploy

### ISSUE THREAD

**Issue by DamiaPoquet** [kubedb/project#691]
I'm trying to deploy KubeDB to use on a new Kubernetes cluster `v1.16.3` following the instructions available on the documentation page.

Tried with KubeDB `v0.12.0` and` v0.13.0-rc.0` with the same results. When I execute the installation command `curl -fsSL https://github.com/kubedb/installer/raw/v0.13.0-rc.0/deploy/kubedb.sh | bash` it is not finishing succesfully. The following error appears:

```
waiting until kubedb operator deployment is ready
timed out waiting for the condition
KubeDB operator deployment failed to be ready
```

Despite of the error, I can see the KubeDB operator running without errors:

```
kubectl get pods --all-namespaces -l app=kubedb
NAMESPACE     NAME                               READY   STATUS    RESTARTS   AGE
kube-system   kubedb-operator-7bc4476899-qg6vd   1/1     Running   0          15m
```
```
I1120 10:03:37.241760       1 run.go:24] Starting kubedb-server...
I1120 10:03:37.881595       1 lib.go:112] Kubernetes version: &version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:13:49Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
I1120 10:03:37.889692       1 controller.go:75] Ensuring CustomResourceDefinition...
I1120 10:03:44.358088       1 run.go:36] Starting KubeDB controller
I1120 10:03:44.359161       1 secure_serving.go:116] Serving securely on [::]:8443
I1120 10:03:47.449484       1 xray.go:232] testing ValidatingWebhook using an object with GVR = kubedb.com/v1alpha1, Resource=redises
I1120 10:03:47.475968       1 apiservice.go:58] Patching APIService v1alpha1.validators.kubedb.com with {"metadata"...
```
It seem to be okay, but it is not usable because catalogs are not installed. For example:
```
kubectl get mysqlversions
No resources found in default namespace.
```

Tell me if you need further information to investigate this.

**Comment by demko** [comment]
@DamiaPoquet I have the same problem.

I noticed the following https://github.com/kubepack/onessl/releases/tag/v0.13.1
`Replaces apps/v1beta1 with apps/v1 for Kubernetes 1.16+ release`.

It seems it has already been fixed in master by https://github.com/kubedb/installer/pull/19

**Comment by ocordeiro** [comment]
Thanks @demko 

curl -fsSL https://raw.githubusercontent.com/kubedb/installer/89fab34cf2f5d9e0bcc3c2d5b0f0599f94ff0dca/deploy/kubedb.sh | bash

works for me

**Comment by fjammes** [comment]
Thanks @demko , above command works for me also. Maybe you should update documentation for v0.13.0-rc.0 in order to ease end-users life?
