### ISSUE TITLE
Is it possible to add plugins to an Elasticsearch?

### ISSUE THREAD

**Issue by gobengo** [kubedb/project#694]
I'd like to use kubedb Elasticsearch, but with the ICU Plugin: https://www.elastic.co/guide/en/elasticsearch/plugins/current/analysis-icu.html

Is it possible to do this with kubedb?

**Comment by Peipeilvcm** [comment]
@gobengo  set ENV in spec.podTemplate.spec.env, `ES_PLUGINS_INSTALL: analysis-icu` you can refer to  https://kubedb.com/docs/0.12.0/concepts/databases/elasticsearch/

**Comment by gobengo** [comment]
@Peipeilvcm omg thanks!
