### ISSUE TITLE
Postgres: Split brain situation after network loss

### ISSUE THREAD

**Issue by stephan2012** [kubedb/project#695]
When the network connectivity between the Kubernetes nodes hosting the primary and the replica Postgres instance is lost, both instances spin up read/write enabled causing a split-brain situation. This is a situation you'll never want to find yourself in and I'm wondering if we can make failover more safe by taking a quorum into account. The Kubernetes cluster (through the etcd cluster) ensures a quorum. Can this be used to avoid split-brain scenarios?

We we're experiencing the split-brain situation with this setup:

- Datacenter 1: 1 Kubernetes master node, Kubernetes worker nodes (hosting Postgres primary instance)
- Datacenter 2: 1 Kubernetes master node, Kubernetes worker nodes (hosting Postgres replica instance)
- Datacenter 3: 1 Kubernetes master node

Network connection between datacenter 1 and 2 was temporarily cut.

**Comment by tamalsaha** [comment]
This issue has been resolved in KubeDB release v2021.03.17 . Please open a new bug if you still see this issue.
