### ISSUE TITLE
If docker.CheckDockerImageVersion fails, send an event to analytics

### ISSUE THREAD

**Issue by tamalsaha** [kubedb/project#72]
_From @tamalsaha on June 1, 2017 21:39_

_Copied from original issue: kubedb/operator#59_

**Comment by tamalsaha** [comment]
_From @aerokite on June 2, 2017 3:36_

When you are creating a database, controller validates its version. If it fails to validate, it will push an event.
```
  1m          1m         1         Postgres operator   Warning    Failed               Fail to be ready Postgres: "postgres-demo". Reason: Image kubedb/postgres:9.6-db not found
  1m          1m         1         Postgres operator   Warning    Invalid              Image kubedb/postgres:9.6-db not found
```

But at the very beginning, when controller is starting, It checks some Images whose versions are provided as flags. If operator fails to validate, It will not move forward. It gives error with `log.Fatalf` because operator will not actually work properly

**Comment by tamalsaha** [comment]
> But at the very beginning, when controller is starting, It checks some Images whose versions are provided as flags. If operator fails to validate, It will not move forward. It gives error with log.Fatalf because operator will not actually work properly

That sounds good. But we should still collect analytics for these events.

**Comment by aerokite** [comment]
We do not validate docker vesion anymore
