### ISSUE TITLE
[0.12.0] PostgresDB strange behavior on initialization from snapshot

### ISSUE THREAD

**Issue by HaveFun83** [kubedb/project#743]
When we try to initialize a postgresDB from s3 snapshot i got the following error
```
E0421 13:15:56.831252       1 workqueue.go:54] failed to complete initialization. Reason: secrets "osm-codimd-postgres-20200421-052902" already exists
E0421 13:15:56.889788       1 worker.go:76] Failed to process key codimd/codimd-v2-postgres. Reason: failed to complete initialization. Reason: secrets "osm-codimd-postgres-20200421-052902" already exists
```
Which lead to a a failed postgreses.kubedb.com object.
The database was created from snapshot but the specified prometheus-servicemonitor and backupjob within the kubedb-postgres manifest was not

As workaround i restarted the kubedb-operator pod which than run a patch on **all postgres objects** which lead to a restart on all postgres pods :(
After this the prometheus-servicemonitor and backupjob was created and the postgres shows status Running.

But the the annotation was still missing
>As a final step of initialization, KubeDB Job controller adds kubedb.com/initialized annotation in initialized Postgres object. This prevents further invocation of initialization process.

Added manually via
`kubectl annotate postgreses.kubedb.com <restored-postgresdb> kubedb.com/initialized=""`

Don't know if this is the right syntax for this?

The main point here should be that the kubedb-opeator should not run a restart on all running postgres instances after a pod restart.

Can you have a look into this? Thx

**Comment by jilleJr** [comment]
Hi, we're experiencing the same issue.

It did not update the `postgreses.kubedb.com` object with the annotation, contrary to [what the documentation states](https://kubedb.com/docs/0.12.0/guides/postgres/initialization/snapshot_source/), but it did complete the snapshot restoration. The `postgreses.kubedb.com` object remained in `Running` state, but if we tried to restart the kubedb operator it retried the snapshot restoration and then failed, and then put the `postgreses.kubedb.com` object in state `Failed`.

Manually setting the annotation as @HaveFun83 suggested did keep it in `Running` state even after a reboot of the operator.

We're using KubeDB 0.12.0 with Postgres 11.2. 

We're unable to find documentation on how to create snapshots in the newer versions of the documentation (ex: [v2020.12.10](https://kubedb.com/docs/v2020.12.10/)). Has that feature of specifying snapshots as their own objects been removed or how do we work with snapshots in the newer versions?

//Kind regards

**Comment by hossainemruz** [comment]
Hi kalle,
KubeDB database backup now has been moved into our specialized backup tool called Stash (https://stash.run/).
You can find the respective documentation for PostgreSQL backup using Stash here (https://stash.run/docs/v2020.12.17/addons/postgres/).

Regards,

Md. Emruz Hossain
Software Engineer, AppsCode Ltd.

Mobile: +8801770582121

**Comment by jilleJr** [comment]
@hossainemruz Thanks for your reply!

Is there a way to migrate from kubedb snapshots to stash backup configuration? Is it automatic when I upgrade my KubeDB operator via helm, or do I lose the snapshots, or do I have to do some manual migration?

**Comment by hossainemruz** [comment]
>Is there a way to migrate from kubedb snapshots to stash snapshot?

No

>Is it automatic when I upgrade my KubeDB operator via helm, or do I lose the snapshots, or do I have to do some manual migration?

Manual.

**Comment by jilleJr** [comment]
@hossainemruz Huh ok, that's less nice, kind of like a show stopper for us.

Since what version did this extraction of Stash happen?
Is this error a known error, or are there any possibility that this would be backported to the pre-Stash version?

**Comment by hossainemruz** [comment]
>Since what version did this extraction of Stash happen?

From v0.14.0.

>are there any possibility that this would be backported to the pre-Stash version?

Lots of things has changed. We have changed our licensing model, redesigned the APIs. The code base has gone through major refactoring. We no longer provide fix for older versions.

**Comment by tamalsaha** [comment]
This is not relevant in recent releases like v2021.03.17 . Please open new issues if you see any problem in current releases.
