### ISSUE TITLE
Postgres DBs go down when Kubernetes apiserver (master) goes down.

### ISSUE THREAD

**Issue by Dirbaio** [kubedb/project#760]
Kubernetes on GKE version v1.15.11-gke.13
KubeDB version kubedb/operator:v0.13.0-rc.0

The Postgres images currently use a leader election that uses the Kubernetes API. If the Kubernetes apiserver  goes down, the current leader shuts down after a timeout (which it totally should, to avoid split brain / diverging timelines etc).

In my opinion, one of the nicest features of Kubernetes is that even if the apiserver is down, kubelets continue running everything they were running before, so your applications don't go down. However, this is not true for kubedb-deployed Postgres databases.

This is a problem because it couples the uptime of the apiserver to the application, elevating the impact of apiserver failure from "I can't do deployments, cronjobs aren't running" to "the entire service is down". Many organizations might want HA applications but not HA apiserver, due to cost or complexity.

The ideal alternative would be to have the database pods do leader election among themselves without depending on the Kubernetes API. Something like an embedded Raft? (I'm not a distributed consensus system expert). 

Another option would be using an independent service to do leader election. Similar to what Patroni does in etcd datastore mode.

**Comment by tamalsaha** [comment]
This issue has been resolved in KubeDB release v2021.03.17 . Please open a new bug if you still see this issue.
