### ISSUE TITLE
Postgres: Helm dependency issue with the PostgresVersion CRD

### ISSUE THREAD

**Issue by parak** [kubedb/project#780]
Hi,

I have a helm chart where I define and template a custom version and image of Postgres using the documentation [here](https://kubedb.com/docs/v0.13.0-rc.0/concepts/catalog/postgres/). However, when loading such a helm chart, the following error is thrown:

`Error: admission webhook "postgres.validators.kubedb.com" denied the request: postgresversions.catalog.kubedb.com "db-custom" not found`

If I manually template the PostgresVersion CRD and insert it via kubectl apply, then the rest of the helm chart installs fine. Is it possible to install both the PostgresVersion and regular Postgres CRDs in the same helm chart? Perhaps by the latter not immediately erroring out and retrying until helm has a chance to apply the former?

Thanks!

**Comment by tamalsaha** [comment]
This has been fixed in KubeDB/Stash v2021.03.17
