### ISSUE TITLE
Redis Can't modify Transparent Huge Pages (THP) through initContainers

### ISSUE THREAD

**Issue by shuinoo** [kubedb/project#790]
i want to chang "echo never > /sys/kernel/mm/transparent_hugepage/enabled" 
create Pod redis-cluster-shard0-1 in StatefulSet redis-cluster-shard0 failed error: Pod "redis-cluster-shard0-1" is invalid: spec.initContainers[0].volumeMounts[0].name: Not found: "host-sys"

**Comment by tamalsaha** [comment]
Use this helm chart
https://github.com/kmodules/installer/tree/master/charts/prepare-kubernetes-cluster
