### ISSUE TITLE
pg-coordinator error: Failed on getting Auth credential

### ISSUE THREAD

**Issue by rena2damas** [kubedb/project#846]
Having this error which I don't seem to be able to get rid of.

```
E0911 15:48:12.522436       1 ha_postgres.go:147] Failed while trying to update wal position in pg-coordinator. Error : Failed to create postgres client engine.: Failed on getting Auth credential.: secrets "ha-postgres-auth" not found
```

I think I have created that secret previously , and somehow that secret seems cached somewhere, don't know why I am still seeing this value.

**Comment by rena2damas** [comment]
And where is the source code for the ```pg-coordinator```, I don't seem to find it therefore I can't troubleshoot the issue

**Comment by tamalsaha** [comment]
This has been fixed in v2021.09.09 release.

**Comment by rena2damas** [comment]
@tamalsaha can you point me to the project & and PR where this issue was fixed ?

**Comment by rena2damas** [comment]
@tamalsaha I cannot upgrade, that version only works on ```demo``` namespace.. I did the upgrade but then had to revert it. My production environment is now broken, I need to apply the fix on this.

**Comment by tamalsaha** [comment]
We have decided to change what is available as part of the free Community Edition. https://blog.byte.builders/post/kubedb-v2021.08.23/ 

If you are interested in purchasing an Enterprise Edition, please drop us a line here: https://appscode.com/contact/

**Comment by rena2damas** [comment]
I understand and we have talked about acquiring a license for it. But for the time being, I need to fix the issue. I am trying to make a case that HA db is helpful but if the current setup does not work, then I am afraid the decision will be going to an alternative db manager.

**Comment by tamalsaha** [comment]
You can try the Enterprise license for free for 30 days. This should allow you to update the operator to the latest version and try the fix now. You can get a 30 day free trial license from here: https://license-issuer.appscode.com/?p=kubedb-enterprise . If you are having any issue, please leave a message here.
