### ISSUE TITLE
MySQL: Support labeling pod

### ISSUE THREAD

**Issue by tal-ayalon** [kubedb/project#847]
I can't find a way to label mysql pod.
I used spec.podTemplate.metadata and it only applied to the statefull set.
Labeling pod is a very important feature for our product

**Comment by tamalsaha** [comment]
Thanks, Tal. I can confirm the issue at code level.

The bug is here: https://github.com/kubedb/mysql/blob/569e220f9fb07da77c06110242aabfc903687dd0/pkg/controller/statefulset.go#L106

We are going to fix it in the next release.

**Comment by tamalsaha** [comment]
Fixed in master. Will be available in upcoming v2021.11.18 release.

**Comment by tamalsaha** [comment]
Hi tal,
Please note, this support has been added in v2021.11.24 release. You can find the release notes here: https://blog.byte.builders/post/kubedb.v2021.11.24/
