### ISSUE TITLE
Add support for OpenSearch in KubeDB managed Elasticsearch

### ISSUE THREAD

**Issue by kamolhasan** [kubedb/project#850]
1. `ES_JAVA_OPTS` ---> `OPENSEARCH_JAVA_OPTS` 
2. Config directory: `/usr/share/opensearch/config/`
3. Security config directory: `/usr/share/opensearch/plugins/opensearch-security/securityconfig/`
4. security admin script directory: `./plugins/opensearch-security/tools/securityadmin.sh`
4. `elasticsearch.yml` --> `opensearch.yml`
4. `opensearch_security.ssl.transport.pemcert_filepath` --> `plugins.security.ssl.transport.pemcert_filepath`
5. In internal users `opendistro_security_roles` --> `opensearch_security_roles`

**Comment by tamalsaha** [comment]
Done!
