### ISSUE TITLE
no matches for kind "ElasticsearchVersion","MariaDBVersion".... in version "catalog.kubedb.com/v1alpha1"

### ISSUE THREAD

**Issue by mcfly722** [kubedb/project#869]
Hello,
just trying to deploy KubeDB by this instruction https://kubedb.com/docs/v2022.05.24/setup/install/community/

On applying final yaml file generated from Helm Template, some objects in k8s created successfully, but for others get next errors:

unable to recognize "KubeDB.yaml": no matches for kind "**ElasticsearchVersion**" in version "catalog.kubedb.com/v1alpha1"
unable to recognize "KubeDB.yaml": no matches for kind "**MariaDBVersion**" in version "catalog.kubedb.com/v1alpha1"
unable to recognize "KubeDB.yaml": no matches for kind "**MemcachedVersion**" in version "catalog.kubedb.com/v1alpha1"
unable to recognize "KubeDB.yaml": no matches for kind "**MongoDBVersion**" in version "catalog.kubedb.com/v1alpha1"
unable to recognize "KubeDB.yaml": no matches for kind "**MySQLVersion**" in version "catalog.kubedb.com/v1alpha1"
unable to recognize "KubeDB.yaml": no matches for kind "**PerconaXtraDBVersion**" in version "catalog.kubedb.com/v1alpha1"
unable to recognize "KubeDB.yaml": no matches for kind "**PgBouncerVersion**" in version "catalog.kubedb.com/v1alpha1"
unable to recognize "KubeDB.yaml": no matches for kind "**PostgresVersion**" in version "catalog.kubedb.com/v1alpha1"
unable to recognize "KubeDB.yaml": no matches for kind "**ProxySQLVersion**" in version "catalog.kubedb.com/v1alpha1"
unable to recognize "KubeDB.yaml": no matches for kind "**RedisVersion**" in version "catalog.kubedb.com/v1alpha1"

What's wrong with it? Maybe some requirement skipped in docs?

**Comment by tamalsaha** [comment]
Can't reproduce!
