### ISSUE TITLE
kafka: Kafka connect

### ISSUE THREAD

**Issue by tamalsaha** [kubedb/project#916]
**Source**
  - [ ] MongoDB
  - [ ] Postgres
 
**Sink**
  - [ ] GCS
  - [ ] S3

**Comment by siegenthalerroger** [comment]
Am I to understand that kubedb supports deploying Kafka connect clusters in distributed mode now? I couldn't find any documentation of this or any way of defining connectors or similar.

**Comment by tamalsaha** [comment]
Yes, kafka connect cluster is distributed mode is now supported. You can find examples here: https://github.com/kubedb/samples/tree/master/kafka

More detailed documentation will be added soon.
