### ISSUE TITLE
Snapshot jobs must have Node:List permission

### ISSUE THREAD

**Issue by tamalsaha** [kubedb/project#98]
I have added analytics to osm and this needs Node.List permission to work.

- Main StatefulSet, / Deployment
- Create snapshot job
- Restore job

**Comment by tamalsaha** [comment]
- [ ] Postgres
- [ ] ES
- [ ] MySQL
- [ ] MongoDB

**Comment by tamalsaha** [comment]
Example: https://github.com/appscode/voyager/blob/master/pkg/ingress/rbac.go

**Comment by aerokite** [comment]
Now we do not need Node:List permission in job. We are passing analytics ClientID as ENV
